import React from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

export const LANGUAGES = {
  ar: { key: 'ar', label: 'العربية', nativeLabel: 'العربية', direction: 'rtl' },
  fr: { key: 'fr', label: 'Français', nativeLabel: 'Français', direction: 'ltr' },
  en: { key: 'en', label: 'English', nativeLabel: 'English', direction: 'ltr' },
};

const STORAGE_KEY = '@kilix_language';
let activeLanguage = 'ar';

// UI translations. Arabic remains the source language; keys not present are intentionally
// returned unchanged so dynamic/product/user data is never corrupted.
const EN = {
  'اللغة':'Language','\n⚠️ تم إنشاء المتجر، لكن تعذر رفع صورة المتجر. يمكنك المحاولة لاحقاً.':'\n⚠️ Store created, but the store image could not be uploaded. You can try again later.','،':',','؟':'?','وضع "عدم الإزعاج"':'Do not disturb mode','الإشعارات':'Notifications','غير متاح':'Unavailable','معلوماتي الشخصية':'Personal information','يحتاج البحث بالصورة إلى استخدام الكاميرا. يُرجى تفعيل الصلاحية من إعدادات الجهاز.':'Image search needs camera access. Please enable the permission in device settings.','يحتاج البحث بالصورة إلى الوصول لمعرض الصور. يُرجى تفعيل الصلاحية من إعدادات الجهاز.':'Image search needs photo library access. Please enable the permission in device settings.','تعتمد الكمية الدنيا (MOQ) على نوع المنتج والمورد. بعض الموردين يقبلون طلبات صغيرة تبدأ من 50 قطعة، بينما يشترط آخرون حاويات كاملة. نحن نساعدك في التفاوض على أقل كمية ممكنة.':'The minimum order quantity (MOQ) depends on the product and supplier. Some suppliers accept small orders starting at 50 pieces, while others require full containers. We help you negotiate the lowest possible quantity.','تم تسجيل الدخول بنجاح':'Signed in successfully','تم إنشاء الحساب بنجاح':'Account created successfully','❌ خطأ إنشاء الحساب:':'❌ Account creation error:','❌ خطأ تسجيل الدخول:':'❌ Login error:','❌ خطأ في العملية:':'❌ Operation error:','🟡 محاولة إنشاء حساب:':'🟡 Account creation attempt:','🟡 محاولة تسجيل الدخول:':'🟡 Login attempt:','🟡 نتيجة إنشاء الحساب:':'🟡 Account creation result:','🟡 نتيجة تسجيل الدخول:':'🟡 Login result:','✅ إنشاء الحساب نجح':'✅ Account creation succeeded','✅ تسجيل الدخول نجح':'✅ Login succeeded',

  'المتجر غير موجود':'Store not found','تعذر تحميل المتجر':'Unable to load store','حاول مرة أخرى.':'Try again.','تسجيل الدخول مطلوب':'Login required','سجل دخولك لمتابعة المتجر.':'Log in to follow this store.','تعذر تحديث المتابعة':'Unable to update follow status','سجل دخولك لمراسلة صاحب المتجر.':'Log in to message the store owner.','المتجر':'Store','تعذر فتح المحادثة':'Unable to open chat','متجر Kilix':'Kilix Store','إلغاء المتابعة':'Unfollow','متابعة':'Follow','حذف الحساب نهائيًا':'Delete account permanently','إلغاء':'Cancel','حذف الحساب':'Delete account','تعذر حذف الحساب':'Unable to delete account','المستخدم':'User','رقم الهاتف غير مضاف':'Phone number not added',
  'الحساب والإعدادات':'Account & settings','المعلومات الشخصية':'Personal information','التنبيهات':'Notifications','الدولة':'Country','الجزائر':'Algeria','العملة':'Currency','الدينار الجزائري (DZD)':'Algerian dinar (DZD)','الطلبات والمعاملات':'Orders & transactions','متجرك':'Your store','إدارة منتجاتك وعرضك التجاري':'Manage your products and storefront','الدعم والمساعدة':'Support & help','مركز المساعدة':'Help center','عن Kilix':'About Kilix','السياسات القانونية':'Legal policies','سياسة الخصوصية العامة':'General privacy policy','فتح رابط السياسة خارج التطبيق':'Open the policy link outside the app',
  'مشكلة في الدفع':'Payment issue','الشحن والتتبع':'Shipping & tracking','الحساب':'Account','أخرى':'Other','يرجى كتابة رسالتك قبل الإرسال':'Please write your message before sending','إرسال طلب آخر':'Send another request','العودة للرئيسية':'Back to home','اكتب رسالتك هنا...':'Write your message here...','إرسال':'Send','البلد':'Country','ستُبلَّغ فور إطلاق الخدمة في بلدك.':'You will be notified as soon as the service launches in your country.','متاح':'Available','قريباً':'Coming soon','تأكيد الاختيار':'Confirm selection',
  'إلكترونيات':'Electronics','نسيج وملابس':'Textiles & clothing','أدوات منزلية':'Home supplies','بناء وإنشاء':'Construction & building','للنساء':'Women','الإلكترونيات':'Electronics','إكسسوارات للأزياء':'Fashion accessories','المجوهرات':'Jewelry','ملابس و أحذية':'Clothing & shoes','ألعاب وهوايات':'Toys & hobbies','الأمن و الحماية':'Security & protection','الأمهات و الأطفال':'Mothers & children','الجمال والصحة':'Beauty & health','للسيارات':'Cars','أخرى':'Other',
  'أبيض':'White','أسود':'Black','أزرق':'Blue','أزرق داكن':'Dark blue','رمادي':'Gray','فضي':'Silver','ذهبي':'Gold','أسود عسكري':'Military black','أحمر':'Red','أحمر خمري':'Burgundy','أخضر':'Green','أصفر':'Yellow','برتقالي':'Orange','وردي':'Pink','بنفسجي':'Purple','بني':'Brown','بيج':'Beige','فيروزي':'Turquoise','أزرق سماوي':'Sky blue',
  'أزياء وملابس':'Fashion & clothing','حواسيب وأجهزة':'Computers & devices','هواتف ذكية':'Smartphones','ساعات وإكسسوارات':'Watches & accessories','أجهزة منزلية':'Home appliances','دج':'DZD','تعذر فتح متجر التطبيقات. يرجى المحاولة مرة أخرى.':'Unable to open the app store. Please try again.','تعذر فتح متجر التطبيقات.':'Unable to open the app store.','قيد الانتظار':'Pending','قيد الشحن':'Shipping','تم الاستلام':'Received','مكتمل':'Completed','نفد المخزون':'Out of stock','ملغاة':'Cancelled','مكتب التوصيل':'Delivery office','البيت':'Home','غير محدد':'Not specified','عام':'General','تعذّر تحديث الطلبية.':'Unable to update the order.',
  'يرجى إدخال اسم المنتج والسعر والوصف.':'Please enter the product name, price and description.','يجب إنشاء المتجر أولاً.':'You must create the store first.','الحد الأدنى والحد الأقصى للطلب غير صالحين.':'The minimum and maximum order quantities are invalid.','حدث خطأ أثناء نشر المنتج.':'An error occurred while publishing the product.','تم تعديل المنتج بنجاح!':'Product updated successfully!','تعذّر حفظ التعديلات.':'Unable to save changes.','تم حذف المنتج وإزالته من إدارة المخزن والعرض بنجاح.':'Product deleted successfully from inventory and storefront.','تعذّر حذف المنتج.':'Unable to delete product.','حدث خطأ أثناء محاولة المشاركة':'An error occurred while sharing','خطأ: لم يتمكن من تحديد معرف المتجر.':'Error: could not determine store ID.','تم رفع الصورة بنجاح!':'Image uploaded successfully!','فشل رفع الصورة. يرجى المحاولة مرة أخرى.':'Image upload failed. Please try again.','يمكنك رفع فيديو واحد فقط لكل منتج.':'You can upload only one video per product.','تم رفع الفيديو بنجاح!':'Video uploaded successfully!','فشل رفع الفيديو. يرجى المحاولة مرة أخرى.':'Video upload failed. Please try again.','تعذر اختيار صورة المتجر.':'Unable to select store image.','يرجى إدخال اسم المتجر ونوع المنتجات على الأقل.':'Please enter at least the store name and product type.','خطأ: لم يتم التعرف على المستخدم الحالي.':'Error: current user was not identified.','حدث خطأ أثناء الاتصال بقاعدة البيانات.':'An error occurred while connecting to the database.',
  'حسابي':'My account','إدارة الطلبات':'Order management','إدارة المخزون':'Inventory management','السجل':'History','تغيير الصورة':'Change image','رفع صورة بروفايل':'Upload profile image','أدخل اسم المتجر':'Enter store name','مثال: أزياء وملابس، هواتف ذكية...':'Example: fashion & clothing, smartphones...','اكتب وصفاً موجزاً عن متجرك...':'Write a short description of your store...','اسم المنتج':'Product name','وصف المنتج':'Product description','مثال: 1':'Example: 1','مثال: 100':'Example: 100','جارٍ الرفع...':'Uploading...','رفع صورة':'Upload image','أدخل اسم المنتج':'Enter product name','مثال: 3500':'Example: 3500','تفاصيل إضافية عن المنتج...':'Additional product details...','جارٍ النشر...':'Publishing...','حفظ المنتج':'Save product','مقاس':'Size','سعة تخزين':'Storage capacity','لون':'Color','مثال: 6XL أو 56':'Example: 6XL or 56','مثال: 128GB':'Example: 128GB','مثال: 2TB':'Example: 2TB','مثال: تركوازي فاتح':'Example: light turquoise','تم تسجيل الدفعة في سجل المدفوعات.':'Payment recorded in the payment history.','تعذر تسجيل الدفعة.':'Unable to record payment.','غير متوفر':'Unavailable','غير متوفرة':'Unavailable','لا توجد ملاحظة':'No note','المنتج':'Product',
  'البحث عن المنتج واختيار المورد':'Find the product and choose a supplier','ابحث عن المنتج باستخدام الكلمات المفتاحية أو الصورة، واختر المصنع أو المورد المناسب من بين المصانع الصينية الموثقة.':'Search by keywords or image and choose a suitable manufacturer or supplier from verified Chinese factories.','إرسال طلب الاستيراد':'Submit import request','أرسل طلبك عبر المنصة، وسنحوله مباشرة إلى شركة الشحن الشريكة للتواصل مع المصنع والتحقق من السعر والتوفر.':'Submit your request through the platform; we will forward it directly to the partner shipping company to contact the factory and verify price and availability.','تأكيد السعر والشحن':'Confirm price & shipping','تتواصل شركة الشحن مع المصنع لتأكيد السعر النهائي، وتحدد أفضل طريقة للشحن (بحري أو جوي)، ثم تعرض عليك التكلفة النهائية للموافقة.':'The shipping company contacts the factory to confirm the final price, chooses the best shipping method (sea or air), then presents the final cost for approval.','الدفع وبدء التنفيذ':'Payment & execution','بعد موافقتك على السعر النهائي، يتم الدفع، وتبدأ شركة الشحن في استلام البضاعة من المصنع وتجهيزها للشحن.':'After you approve the final price, payment is made and the shipping company collects the goods from the factory and prepares them for shipment.','الشحن والتخليص الجمركي':'Shipping & customs clearance','تتولى شركة الشحن نقل البضاعة، وإنجاز إجراءات التخليص الجمركي، مع تحديث حالة الطلب في كل مرحلة.':'The shipping company transports the goods, handles customs clearance, and updates the order status at every stage.','الاستلام وإغلاق الطلب':'Receipt & order closure','تستلم بضاعتك في الجزائر، وبعد التأكيد على الاستلام يتم إغلاق الطلب بنجاح.':'You receive your goods in Algeria; after confirming receipt, the order is successfully closed.',
  'ما هي أقل كمية يمكنني استيرادها؟':'What is the minimum quantity I can import?','كم تستغرق مدة الشحن من الصين للجزائر؟':'How long does shipping from China to Algeria take?','الشحن الجوي يستغرق عادةً من 7 إلى 12 يوماً، بينما يستغرق الشحن البحري ما بين 35 إلى 45 يوماً للوصول إلى الموانئ الجزائرية الرئيسية.':'Air shipping usually takes 7–12 days, while sea shipping takes 35–45 days to reach the main Algerian ports.','هل Kilix تضمن جودة المنتجات؟':'Does Kilix guarantee product quality?','نعم، نقدم خدمة فحص الجودة في المصنع قبل الشحن. فريقنا في الصين يقوم بمعاينة البضاعة والتأكد من مطابقتها للمواصفات المتفق عليها قبل إجراء الدفع النهائي للمورد.':'Yes. We provide factory quality inspection before shipping. Our team in China checks the goods and verifies they meet the agreed specifications before final supplier payment.','كيف يتم حساب تكلفة الجمارك؟':'How are customs costs calculated?','تُحسب التكلفة بناءً على تعريفة الجمارك الجزائرية المخصصة لنوع المنتج (Code SH) وقيمة الفاتورة وتكاليف التأمين والشحن. نقدم لك استشارة تقديرية قبل البدء.':'Costs are calculated based on the Algerian customs tariff for the product type (HS Code), invoice value, insurance and shipping costs. We provide an estimate before you start.','دليل الاستخدام':'User guide','تصنيفات المنتجات':'Product categories','الرئيسية':'Home',
  'تعذر حفظ الإعدادات':'Unable to save settings','إعدادات الإشعارات':'Notification settings','تحديثات الشحن':'Shipping updates','تغيير حالة الطلبية وحالتها':'Order status changes','تنبيهات نفاد المخزون':'Low stock alerts','الرسائل':'Messages','رسائل المحادثات الخاصة وتأكيدات الطلبات':'Private chat messages and order confirmations','التقييمات والمتابعات':'Reviews & follows','تقييمات المنتجات والمتابعون الجدد':'Product reviews and new followers','تنبيهات الدفع':'Payment alerts','تسجيل الدفعات والفواتير':'Payment records and invoices','تنبيهات النظام':'System alerts','التحديثات العامة للحساب':'General account updates','وضع "عدم الإزعاج"':'Do not disturb mode','كتم الإشعارات في أوقات محددة':'Mute notifications at specific times','أمس':'Yesterday','البحث في الرسائل...':'Search messages...','توصيل آمن':'Safe delivery','دفع عند الاستلام':'Cash on delivery','ز.م':'K.M','مستخدم':'User',
  'تفاصيل المنتج':'Product details','هذا المنتج لم يعد متاحاً من طرف التاجر.':'This product is no longer available from the seller.','يرجى ملء الاسم، اللقب، رقم الهاتف، والولاية.':'Please fill in first name, last name, phone number and state.','يرجى اختيار البلدية وإدخال الشارع لتوصيل المنزل.':'Please choose the municipality and enter the street for home delivery.','يرجى اختيار البلدية (مكتب التوصيل).':'Please choose the municipality (delivery office).','تعذّر تحديد بيانات المنتج أو المتجر، يرجى المحاولة لاحقاً.':'Unable to determine product or store data. Please try again later.','تعذّر إرسال الطلب، يرجى المحاولة مرة أخرى.':'Unable to submit the order. Please try again.','لا تقييم بعد':'No reviews yet','المنتج غير متاح حالياً':'Product currently unavailable','اختر الكمية والخيارات':'Choose quantity and options','تم حذف المنتج من مخزون التاجر ولا يمكن استقبال طلبات جديدة.':'The product was removed from the seller inventory and new orders cannot be accepted.','إجراء طلب':'Place order','أدخل أي تفاصيل إضافية هنا...':'Enter any additional details here...','أضف إلى السلة':'Add to cart','إنشاء طلبية':'Create order','أدخل الاسم واللقب':'Enter first and last name','اختر الولاية (69 ولاية)':'Choose state (69 states)','اختر البلدية التابعة للولاية':'Choose the municipality in the state','أدخل اسم الشارع أو الحي ورقم المنزل':'Enter street/neighborhood and house number','استمرار':'Continue','الذهاب إلى السلة':'Go to cart','متابعة التسوق':'Continue shopping',
  'سياسة ملفات تعريف الارتباط':'Cookie policy','توريد مباشر':'Direct sourcing','تواصل مباشر مع الموردين':'Direct communication with suppliers','شحن موثوق':'Reliable shipping','شحن امن ودفع عند الاستلام':'Secure shipping and cash on delivery','أمان المعاملات':'Transaction security','معاملا امنة وتوثيق كامل للطلبات':'Secure transactions and full order verification','منتج متاح':'Available product','تاجر نشط':'Active seller','شركة شحن':'Shipping company','تاجر مسجل':'Registered seller','دينار جزائري':'Algerian dinar','د.ت':'TND','تونس':'Tunisia','دينار تونسي':'Tunisian dinar','د.م':'MAD','المغرب':'Morocco','درهم مغربي':'Moroccan dirham','د.ل':'LYD','ليبيا':'Libya','دينار ليبي':'Libyan dinar','حقوق المحتوى':'Content rights','ملغى':'Cancelled','الطلبية':'Order','قطعة':'piece','مكتب':'Office','المنزل':'Home','تتبع الطلبية':'Track order','شروط الاستخدام':'Terms of use','متاجر متنوعة':'Various stores','الآن':'Now','المحادثة':'Chat','تعذّر إرسال الرسالة':'Unable to send message','تعذّر الإرسال':'Send failed','لم تُرسَل رسالتك، يرجى المحاولة مرة أخرى.':'Your message was not sent. Please try again.','تم إلغاء تثبيت المحادثة':'Chat unpinned','تم تثبيت المحادثة':'Chat pinned','حذف المحادثة':'Delete chat','هل أنت متأكد؟':'Are you sure?','حذف':'Delete','تعذّر حذف المحادثة':'Unable to delete chat','تعذر حذف المحادثة':'Unable to delete chat','اكتب رسالة...':'Write a message...','الكل':'All','يناير':'January','فبراير':'February','مارس':'March','أبريل':'April','ماي':'May','جوان':'June','جويلية':'July','أوت':'August','سبتمبر':'September','أكتوبر':'October','نوفمبر':'November','ديسمبر':'December',
  'تعذر تأكيد الاستلام':'Unable to confirm receipt','يرجى المحاولة مرة أخرى.':'Please try again.','ابحث في طلباتك':'Search your orders','تأكيد استلام الطلب':'Confirm order receipt','سياسة الخصوصية':'Privacy policy','إجمالي الدعوات':'Total invitations','إحالات ناجحة':'Successful referrals','إحالات معلّقة':'Pending referrals','إجمالي المكافآت':'Total rewards','تعذر إرسال التقييم':'Unable to submit review','تقييم الطلب':'Rate order','طلبك':'Your order','اكتب تعليقك عن المنتج وتجربة الشراء...':'Write your comment about the product and shopping experience...','إرسال التقييم':'Submit review','مستورد / تاجر':'Importer / seller','الاسم الكامل':'Full name','رقم الهاتف':'Phone number','الولاية':'State','البريد الإلكتروني':'Email','يرجى تعبئة جميع الحقول':'Please fill in all fields','البريد الإلكتروني غير صحيح':'Invalid email','كلمة المرور خاطئة':'Incorrect password','البريد الإلكتروني أو كلمة المرور غير صحيحة':'Incorrect email or password','حدث خطأ أثناء تسجيل الدخول، يرجى المحاولة لاحقاً':'Login failed. Please try again later','يرجى تعبئة جميع الحقول المطلوبة':'Please fill in all required fields','كلمتا المرور غير متطابقَتين':'Passwords do not match','كلمة السر يجب أن تكون 6 أحرف على الأقل':'Password must be at least 6 characters','هذا البريد الإلكتروني مسجل مسبقاً أو غير صالح':'This email is already registered or invalid','حدث خطأ أثناء إنشاء الحساب، يرجى المحاولة لاحقاً':'Account creation failed. Please try again later','المتابعة أو':'Continue with','أدخل البريد الإلكتروني':'Enter email','أدخل كلمة السر':'Enter password','أدخل الاسم':'Enter first name','أدخل اللقب':'Enter last name','أدخل رقم الهاتف':'Enter phone number','أدخل كلمة السر (6 أحرف على الأقل)':'Enter password (at least 6 characters)','أعد إدخال كلمة السر':'Re-enter password','تم إرسال رمز التحقق.':'Verification code sent.','يرجى إدخال رمز التحقق.':'Please enter the verification code.','يرجى إدخال رمز التحقق كاملاً.':'Please enter the complete verification code.','انتهت صلاحية رمز التحقق.':'Verification code expired.','تم إنشاء الحساب بنجاح.':'Account created successfully.','تأكيد والدخول':'Confirm & sign in',
  'صلاحية الوصول مرفوضة':'Permission denied','فتح الإعدادات':'Open settings','صلاحية الكاميرا مرفوضة':'Camera permission denied','تعذّر تجهيز الصورة للبحث':'Unable to prepare image for search','الأبعاد الأصلية':'Original dimensions','مربع':'Square','قياسي':'Standard','عريض':'Wide','أصلي':'Original','مثال: حقيبة سوداء جلدية':'Example: black leather bag','رفع الصورة':'Upload image','تحليل المحتوى':'Analyzing content','استخراج النتائج':'Extracting results','ابحث عن منتجات...':'Search products...','ابحث عن منتجات، موردين...':'Search products, suppliers...','جارٍ تحميل المزيد...':'Loading more...','اسحب للأسفل لرؤية المزيد':'Pull down to see more','لإتمام طلبك بأمان وتتبعه لاحقاً':'To complete and track your order securely','لحفظ سلتك وإدارة مشترياتك بسهولة':'To save your cart and manage purchases easily','مجموعات الاختيار':'Option groups','مقلوبة الترتيب':'Reversed order','يرجى إدخال البريد الإلكتروني.':'Please enter your email.','يرجى إدخال بريد إلكتروني صحيح.':'Please enter a valid email.','يرجى إدخال كلمة سر لا تقل عن 6 أحرف.':'Please enter a password of at least 6 characters.','كلمة السر':'Password','جاري المعالجة...':'Processing...','طلباتي':'My orders','طلبات مكتملة':'Completed orders','إجمالي المشتريات':'Total purchases','توفير إجمالي':'Total savings','ادعُ تاجراً واربح!':'Invite a seller and earn!','شارك رابطك واحصل على خصومات':'Share your link and get discounts','مشاركة':'Share','تسجيل الخروج':'Log out','سيتم حذف حسابك نهائيًا، بما في ذلك بريدك الإلكتروني وبياناتك الشخصية ومتجرك ومنتجاته وصوره وفيديوهاته والبيانات المرتبطة بحسابك. لا يمكن التراجع عن هذه العملية.':'Your account will be permanently deleted, including your email, personal data, store, products, images, videos and associated data. This action cannot be undone.','طلبية جديدة':'New order','تم تأكيد الطلب':'Order confirmed','تم استلام الطلب':'Order received','اكتملت الطلبية':'Order completed','رسالة جديدة':'New message','تقييم جديد':'New review','متابع جديد':'New follower','الدفع المستحق':'Payment due','وصلت طلبية جديدة إلى متجرك':'A new order has arrived at your store','تم تأكيد طلبك من طرف التاجر وأصبح قيد الشحن':'Your order was confirmed by the seller and is now shipping','نعتذر، المنتج المطلوب غير متوفر حالياً':'Sorry, the requested product is currently unavailable','أكد المشتري استلام الطلب':'The buyer confirmed receipt of the order','تم إكمال الطلب بعد تقييم المشتري':'The order was completed after the buyer’s review','لديك رسالة جديدة في المحادثات':'You have a new message in your chats','تمت إضافة تقييم جديد لمنتجك':'A new review was added to your product','قام مستخدم بمتابعة متجرك':'A user followed your store','وصلت رسوم الاشتراك إلى 500 دج أو أكثر؛ يرجى تسوية الرصيد المستحق.':'Your subscription fees have reached 500 DZD or more; please settle the outstanding balance.','تم تسجيل الدفعة':'Payment recorded','غير مقروء':'unread','قراءة الكل':'Mark all as read','لا توجد إشعارات':'No notifications','ستظهر هنا إشعارات طلباتك ومراسلاتك':'Your order and message notifications will appear here','إعدادات الإشعارات':'Notification settings','إشعارات':'Notifications','الرئيسية':'Home','حسابي':'My account',
  'متابع':'Following',
  'منتج':'Product',
  'تقييم':'Review',
  'مراسلة':'Message',
  'منتجات المتجر':'Store products',
  'لا توجد منتجات منشورة حالياً.':'No products published yet.',
  'تم إرسال طلبك':'Your request was sent',
  'لقد استلمنا رسالتك وسيتواصل معك فريق الدعم قريباً.':'We received your message and our support team will contact you soon.',
  'قنوات التواصل':'Contact channels',
  'اتصل بنا':'Contact us',
  'دردشة مباشرة':'Live chat',
  'متاح ٨ص – ١٠م':'Available 8 AM – 10 PM',
  'أرسل طلب دعم':'Send a support request',
  'سنرد عليك خلال ٢٤ ساعة.':'We will reply within 24 hours.',
  'الموضوع':'Subject',
  'رسالتك':'Your message',
  'متاح الآن':'Available now',
  'اختيار بلد غير متاح حالياً سيضعك في قائمة الانتظار. ستُبلّغ فور إطلاق الخدمة في بلدك.':'Selecting a country that is not currently available will add you to the waiting list. You will be notified when the service launches in your country.',
  'إنشاء متجرك الجديد':'Create your new store',
  'أدخل تفاصيل متجرك أدناه للبدء في إدارة الطلبات والمخزون بكل احترافية.':'Enter your store details below to start managing orders and inventory professionally.',
  'بيانات المتجر الأساسية':'Basic store information',
  'صورة بروفايل المتجر (اختيارية)':'Store profile image (optional)',
  'ستظهر هذه الصورة للمستخدمين في صفحة المنتج وصفحة تفاصيل المتجر.':'This image will appear to users on the product page and store details page.',
  'اسم المتجر':'Store name',
  'نوع المنتجات التي يبيعها المتجر':'Types of products sold by the store',
  'نوع النشاط التجاري':'Business type',
  'بائع جملة':'Wholesaler',
  'مصنع':'Manufacturer',
  'وصف للمتجر':'Store description',
  'لا توجد طلبات حالياً':'No orders yet',
  'تأكيد':'Confirm',
  'نفد':'Out of stock',
  'التفاصيل':'Details',
  'لا توجد منتجات حالياً':'No products yet',
  'تعديل':'Edit',
  'إضافة منتج':'Add product',
  'اضغط على أي معاملة لعرض التفاصيل الكاملة.':'Tap any transaction to view the full details.',
  'لا توجد معاملات حالياً':'No transactions yet',
  'عرض التفاصيل':'View details',
  'تعديل بيانات المنتج':'Edit product details',
  'نموذج المنتج':'Product form',
  'السعر الأساسي (دج)':'Base price (DZD)',
  'تصنيف المنتج':'Product category',
  'خيارات الرام (RAM)':'RAM options',
  'إضافة RAM مخصص':'Add custom RAM',
  'سعات التخزين':'Storage capacities',
  'إضافة تخزين مخصص':'Add custom storage',
  'الأحجام المتوفرة':'Available sizes',
  'إضافة مقاس':'Add size',
  'الألوان المتوفرة':'Available colors',
  'إضافة لون':'Add color',
  'الحد الأدنى للطلب':'Minimum order quantity',
  'الحد الأقصى للطلب':'Maximum order quantity',
  'رفع الصور والفيديوهات':'Upload images and videos',
  'الفيديوهات — متاح قريبًا':'Videos — coming soon',
  'حفظ التعديلات':'Save changes',
  'إضافة منتج جديد':'Add new product',
  'وصف المنتج (اختياري)':'Product description (optional)',
  'إضافة':'Add',
  'كيفية حساب الرسوم':'How fees are calculated',
  'تُحسب الرسوم بنسبة 0.3% من قيمة المنتجات التي تم بيعها فقط.':'Fees are calculated at 0.3% of the value of products sold only.',
  'طريقة الحساب':'Calculation method',
  'قيمة المنتجات × 0.003 = الرسوم':'Product value × 0.003 = fees',
  'مثال 1':'Example 1',
  '30,000 سنتيم':'30,000 centimes',
  'مثال 2':'Example 2',
  '60,000 سنتيم':'60,000 centimes',
  'مثال 3':'Example 3',
  '300,000 سنتيم':'300,000 centimes',
  'إغلاق':'Close',
  'قم بتحديث التطبيق':'Update the app',
  'قم بتحديث التطبيق للاستمرار في الاستفادة من الخدمات وإتمام الدفع.':'Update the app to continue using the services and completing payments.',
  'تحديث التطبيق':'Update app',
  'اختر نوع جهازك':'Choose your device',
  'سيتم نقلك مباشرة إلى صفحة Kilix في متجر التطبيقات.':'You will be taken directly to the Kilix page in the app store.',
  'دفع الرصيد المستحق':'Pay outstanding balance',
  'اختر وسيلة الدفع المناسبة لإتمام التسوية.':'Choose the appropriate payment method to settle the balance.',
  'بريدي موب (BaridiMob)':'BaridiMob',
  'البطاقة الذهبية (Dahabia)':'Dahabia card',
  'حذف المنتج؟':'Delete product?',
  'هل أنت متأكد من رغبتك في حذف هذا المنتج؟ لا يمكن التراجع عن هذا الإجراء.':'Are you sure you want to delete this product? This action cannot be undone.',
  'تمت إضافة المنتج بنجاح':'Product added successfully',
  'أصبح منتجك الجديد متاحاً الآن في المخزون وجاهزاً لاستقبال الطلبات.':'Your new product is now available in inventory and ready to receive orders.',
  'حسناً':'OK',
  'بدون خيارات إضافية':'No additional options',
  'لا توجد تفاصيل مجموعات محفوظة لهذه الطلبية.':'No saved group details for this order.',
  'كيف تستورد من الصين؟':'How do you import from China?',
  'نحن هنا لتبسيط رحلة استيرادك. اتبع هذه الخطوات الست للوصول بمنتجاتك من المصنع في الصين إلى مستودعك في الجزائر.':'We are here to simplify your importing journey. Follow these six steps to get your products from the factory in China to your warehouse in Algeria.',
  'أسئلة شائعة':'Frequently asked questions',
  'عندك سؤال؟':'Have a question?',
  'فريق الدعم الفني لدينا متاح للإجابة على جميع استفساراتكم':'Our technical support team is available to answer all your questions.',
  'من 8:00 صباحاً حتى 10:00 مساءً':'From 8:00 AM to 10:00 PM',
  'تواصل معنا':'Contact us',
  '© 2026 Kilix DZ Sourcing Pass. جميع الحقوق محفوظة.':'© 2026 Kilix DZ Sourcing Pass. All rights reserved.',
  'شروط الخدمة':'Terms of service',
  'تفعيل كافة الإشعارات':'Enable all notifications',
  'تحكم في جميع تنبيهات التطبيق بضغطة واحدة':'Control all app notifications with one tap',
  'الطلبات والشحن':'Orders and shipping',
  'المحادثات والتقييمات':'Chats and reviews',
  'ساعات الهدوء':'Quiet hours',
  'من الساعة':'From',
  '10:00 م':'10:00 PM',
  'إلى الساعة':'To',
  '08:00 ص':'08:00 AM',
  'لا توجد محادثات بعد':'No conversations yet',
  'خيارات المنتج':'Product options',
  'من يوم إلى 4 أيام':'1 to 4 days',
  'مدة الشحن :':'Shipping duration:',
  'تقييمات العملاء':'Customer reviews',
  'لا توجد تقييمات بعد لهذا المنتج':'No reviews yet for this product',
  'شراء مؤكد ✓':'Verified purchase ✓',
  'منتجات قد تعجبك أيضاً':'Products you may also like',
  'السلة':'Cart',
  'تخصيص الطلب':'Customize order',
  'ملاحظات إضافية':'Additional notes',
  'يرجى إكمال كل الخيارات الإلزامية في كل مجموعة والتأكد من توفرها':'Please complete all required options in each group and make sure they are available.',
  'معلومات الشحن والتوصيل':'Shipping and delivery information',
  'الاسم واللقب':'First and last name',
  'طريقة التوصيل':'Delivery method',
  'توصيل للمنزل':'Home delivery',
  'توصيل لمكتب التوصيل':'Delivery office',
  'البلدية':'Municipality',
  'الشارع / الحي':'Street / neighborhood',
  'تم إنشاء طلبية بنجاح!':'Order created successfully!',
  'تم تسجيل طلبك ومعالجته بنجاح، سنتواصل معك قريباً لتأكيد التوصيل.':'Your order was received and processed successfully. We will contact you soon to confirm delivery.',
  'الإصدار 1.2.0':'Version 1.2.0',
  'وسيط ذكي يربط التجار الجملة بتجار التجزئة — بدون وسطاء، بدون تعقيد.':'A smart intermediary connecting wholesalers with retailers — no middlemen, no complexity.',
  'لماذا Kilix؟':'Why Kilix?',
  '© 2026 Kilix · الجزائر':'© 2026 Kilix · Algeria',
  'اختر العملة المفضلة':'Choose your preferred currency',
  'تقدم الطلبية':'Order progress',
  'الحالة الفعلية المسجلة في الطلبية':'Actual status recorded for the order',
  'رقم الطلب':'Order number',
  'طلبية واحدة':'One order',
  'الحالة المسجلة':'Recorded status',
  'لا توجد طلبية للتتبع':'No order to track',
  'افتح التتبع من سجل الطلبات لعرض الحالة الفعلية.':'Open tracking from order history to view the actual status.',
  'تم ترك تعليقك بنجاح.':'Your review was submitted successfully.',
  'سلتك فارغة':'Your cart is empty',
  'أضف منتجات من الصفحة الرئيسية لتظهر هنا':'Add products from the home page to see them here',
  'تصفح المنتجات':'Browse products',
  'سلة التسوق':'Shopping cart',
  'تحديد الكل':'Select all',
  'قراءة الكل':'Mark all as read',
  'لا توجد إشعارات':'No notifications',
  'ستظهر هنا إشعارات طلباتك ومراسلاتك':'Your order and message notifications will appear here',
  'تثبيت المحادثة':'Pin conversation',
  'مشاركة المحادثة':'Share conversation',
  'جارٍ تحميل طلباتك...':'Loading your orders...',
  'لا توجد طلبات في هذا القسم':'No orders in this section',
  'تاريخ الطلب':'Order date',
  'فتح سياسة الخصوصية العامة':'Open general privacy policy',
  'طلب حذف الحساب والبيانات':'Request account and data deletion',
  'لا توجد عروض إحالة متاحة حاليًا.':'No referral offers are currently available.',
  'تحديث':'Refresh',
  'عروض الإحالة':'Referral offers',
  'ادعُ أصدقاءك واكسب مكافآت حصرية':'Invite your friends and earn exclusive rewards',
  'إحصائياتي في الإحالة':'My referral statistics',
  'رابط الإحالة الخاص بك':'Your referral link',
  'الكود':'Code',
  'الرابط':'Link',
  'نسخ الرابط':'Copy link',
  'نسخ الكود':'Copy code',
  'سجل الإحالات':'Referral history',
  'نظام الإحالات غير مفعل في مخطط قاعدة البيانات الحالي.':'The referral system is not enabled in the current database schema.',
  'تم تسليم طلبك بنجاح. شاركنا رأيك لمساعدتنا على التحسّن.':'Your order was delivered successfully. Share your feedback to help us improve.',
  'ما تقييمك للطلب؟':'How would you rate the order?',
  'أضف تعليقك (اختياري)':'Add your comment (optional)',
  'احصل على كوبون خصم بقيمة 500 دج عند ترك تعليق.':'Get a 500 DZD discount coupon when you leave a review.',
  'إنشاء حساب':'Create account',
  'تسجيل الدخول':'Log in',
  'المتابعة كضيف':'Continue as guest',
  'التسوق':'Shopping',
  'تصفح واشتري':'Browse and buy',
  'أنشئ متجرك':'Create your store',
  'آمن':'Secure',
  'مشفر ومحمي':'Encrypted and protected',
  'دخول':'Sign in',
  'ليس لديك حساب؟ اشترك الآن':'Don’t have an account? Sign up now',
  'إنشاء حساب جديد':'Create a new account',
  'الاسم':'First name',
  'اللقب':'Last name',
  'تأكيد كلمة السر':'Confirm password',
  'رجوع':'Back',
  'تأكيد رمز التحقق':'Verify code',
  'إعادة إرسال الرمز':'Resend code',
  'البحث بالصورة':'Image search',
  'بحث':'Search',
  'حدد أبعاد الصورة قبل البحث':'Set the image dimensions before searching',
  'أبعاد البحث':'Search dimensions',
  'ما الذي تبحث عنه تحديدًا؟':'What exactly are you looking for?',
  'اختياري: اكتب نوع المنتج أو اللون أو أي تفصيل تريد التركيز عليه.':'Optional: enter the product type, color, or any detail you want to focus on.',
  'بحث بهذه الصورة':'Search with this image',
  'ابحث بصورة منتج':'Search by product image',
  'التقط صورة أو اختر من معرضك للعثور على منتجات مشابهة في كتالوج Kilix.':'Take a photo or choose one from your gallery to find similar products in the Kilix catalog.',
  'الصلاحية مرفوضة':'Permission denied',
  'يتطلب البحث بالصورة الوصول إلى المعرض أو الكاميرا. افتح إعدادات الجهاز لتفعيل الصلاحية.':'Image search requires access to the gallery or camera. Open device settings to enable permission.',
  'معرض الصور':'Photo gallery',
  'اختر من ألبوماتك':'Choose from your albums',
  'الكاميرا':'Camera',
  'التقط صورة جديدة':'Take a new photo',
  'للحصول على أفضل نتائج، استخدم صورة واضحة للمنتج على خلفية بيضاء أو مُحايدة.':'For best results, use a clear product photo on a white or neutral background.',
  'جاري تحليل الصورة...':'Analyzing image...',
  'نبحث عن المنتجات المشابهة في الكتالوج':'Searching the catalog for similar products',
  'منتجات مشابهة':'Similar products',
  'جرّب صورة أخرى':'Try another image',
  'لا توجد منتجات مشابهة':'No similar products found',
  'لم نتمكن من العثور على منتجات مشابهة لهذه الصورة. جرّب صورة أكثر وضوحاً أو زاوية مختلفة.':'We could not find similar products for this image. Try a clearer image or a different angle.',
  'تعذّر تحليل الصورة':'Unable to analyze image',
  'حدث خطأ أثناء معالجة الصورة. تأكد من الاتصال بالإنترنت وحاول مجدداً.':'An error occurred while processing the image. Check your internet connection and try again.',
  'إعادة المحاولة':'Retry',
  'ابحث عن منتجات':'Search for products',
  'ابدأ بكتابة ما تبحث عنه للعثور على منتجات':'Start typing what you are looking for to find products',
  'لم نجد نتائج':'No results found',
  'جرّب كلمات بحث مختلفة':'Try different search terms',
  'معاملات والمحادثات محمية داخل التطبيق':'Transactions and conversations are protected inside the app',
  'جارٍ تحميل المنتجات...':'Loading products...',
  'لا توجد منتجات في هذا التصنيف حالياً':'No products in this category currently',
  'أنشئ حساباً للمتابعة':'Create an account to continue',
  'متابعة التصفح':'Continue browsing',
  'مطلوب':'Required',
  'مكتملة':'Completed',
  'غير مكتملة':'Incomplete',
  'هذا المنتج لا يحتوي على خيارات إضافية':'This product has no additional options',
  'هذه التوليفة غير متوفرة حالياً، جرّب خياراً آخر':'This combination is currently unavailable, try another option',
  'الكمية':'Quantity',
  'سعر هذه المجموعة':'Price for this group',
  'حدث خطأ غير متوقع':'An unexpected error occurred',
  'للأسف، حدث شيء ما غير صحيح في التطبيق. يرجى المحاولة مرة أخرى.':'Unfortunately, something went wrong in the app. Please try again.',
  '📋 تفاصيل الخطأ:':'📋 Error details:',
  '🔄 إعادة محاولة':'🔄 Try again',
  'العودة':'Go back',
  'إذا استمرت المشكلة، يرجى الاتصال بفريق الدعم.':'If the problem persists, please contact support.',
  'اختر أحد الخيارات التالية للاطلاع على التفاصيل':'Choose one of the following options to view the details',
  'إضافة مجموعة أخرى':'Add another group',
  'عدد المجموعات':'Number of groups',
  'إجمالي الكمية':'Total quantity',
  'السعر الإجمالي':'Total price',
  'تسجيل الدخول أو إنشاء حساب':'Log in or create an account',
  'أدخل بريدك الإلكتروني للمتابعة':'Enter your email to continue',

  'وسيط ذكي يربط التجار الجملة بتجار التجزئة  — بدون وسطاء، بدون تعقيد.':'A smart platform connecting wholesalers with retailers — no middlemen, no complexity.',
  'السعر:':'Price:',
  'قيمة المنتجات المباعة:':'Value of products sold:',
  'أي':'Any',
  'الرسوم:':'Fees:',
  'يتم احتساب الرسوم بنفس النسبة دائمًا:':'Fees are always calculated at the same rate:',
  'من قيمة المنتجات المباعة.':'of the value of products sold.',
  'الاسم:':'Name:',
  'رقم الهاتف:':'Phone number:',
  'الولاية:':'State:',
  'البلدية:':'Municipality:',
  'طريقة التوصيل:':'Delivery method:',
  'عنوان البيت:':'Home address:',
  'نقطة التسليم:':'Delivery point:',
  'مكتب التوصيل في البلدية المحددة':'Delivery office in the selected municipality',
  'الملاحظة:':'Note:',
  'الحالة:':'Status:',
  'المجموع:':'Total:',
  'إجمالي الكمية:':'Total quantity:',
  'العربية':'Arabic',
};

const FR = {
  ...Object.fromEntries(Object.entries(EN).map(([k,v])=>[k,v])),
  'اللغة':'Langue','الإشعارات':'Notifications','غير متاح':'Indisponible','معلوماتي الشخصية':'Informations personnelles','وضع "عدم الإزعاج"':'Mode « Ne pas déranger »','يحتاج البحث بالصورة إلى استخدام الكاميرا. يُرجى تفعيل الصلاحية من إعدادات الجهاز.':'La recherche par image nécessite l’accès à la caméra. Activez l’autorisation dans les paramètres de l’appareil.','يحتاج البحث بالصورة إلى الوصول لمعرض الصور. يُرجى تفعيل الصلاحية من إعدادات الجهاز.':'La recherche par image nécessite l’accès à la galerie. Activez l’autorisation dans les paramètres de l’appareil.','تعتمد الكمية الدنيا (MOQ) على نوع المنتج والمورد. بعض الموردين يقبلون طلبات صغيرة تبدأ من 50 قطعة، بينما يشترط آخرون حاويات كاملة. نحن نساعدك في التفاوض على أقل كمية ممكنة.':'La quantité minimale (MOQ) dépend du produit et du fournisseur. Certains fournisseurs acceptent de petites commandes à partir de 50 pièces, tandis que d’autres exigent des conteneurs complets. Nous vous aidons à négocier la quantité minimale.','❌ خطأ إنشاء الحساب:':'❌ Erreur de création du compte :','❌ خطأ تسجيل الدخول:':'❌ Erreur de connexion :','❌ خطأ في العملية:':'❌ Erreur de traitement :','🟡 محاولة إنشاء حساب:':'🟡 Tentative de création de compte :','🟡 محاولة تسجيل الدخول:':'🟡 Tentative de connexion :','🟡 نتيجة إنشاء الحساب:':'🟡 Résultat de création du compte :','🟡 نتيجة تسجيل الدخول:':'🟡 Résultat de connexion :','✅ إنشاء الحساب نجح':'✅ Création du compte réussie','✅ تسجيل الدخول نجح':'✅ Connexion réussie',
  'العربية':'Arabe','Français':'Français','English':'Anglais','التسوق':'Achats','الحساب والإعدادات':'Compte et paramètres','المعلومات الشخصية':'Informations personnelles','التنبيهات':'Notifications','الدولة':'Pays','الجزائر':'Algérie','العملة':'Devise','الدينار الجزائري (DZD)':'Dinar algérien (DZD)','الطلبات والمعاملات':'Commandes et transactions','متجرك':'Votre boutique','الدعم والمساعدة':'Assistance et aide','مركز المساعدة':'Centre d’aide','عن Kilix':'À propos de Kilix','السياسات القانونية':'Politiques légales','سياسة الخصوصية العامة':'Politique générale de confidentialité','حذف الحساب':'Supprimer le compte','تسجيل الخروج':'Se déconnecter','الرئيسية':'Accueil','طلباتي':'Mes commandes','الرسائل':'Messages','حسابي':'Mon compte','مشاركة':'Partager','متابعة':'Suivre','إلغاء المتابعة':'Ne plus suivre','إرسال':'Envoyer','إلغاء':'Annuler','حذف':'Supprimer','استمرار':'Continuer','الذهاب إلى السلة':'Aller au panier','متابعة التسوق':'Continuer les achats','أضف إلى السلة':'Ajouter au panier','إجراء طلب':'Commander','تفاصيل المنتج':'Détails du produit','اسم المنتج':'Nom du produit','وصف المنتج':'Description du produit','حفظ المنتج':'Enregistrer le produit','تغيير الصورة':'Changer l’image','رفع صورة':'Téléverser une image','جارٍ الرفع...':'Téléversement...','جارٍ النشر...':'Publication...','إعدادات الإشعارات':'Paramètres des notifications','تحديثات الشحن':'Mises à jour de livraison','تنبيهات نفاد المخزون':'Alertes de stock faible','رسائل المحادثات الخاصة وتأكيدات الطلبات':'Messages privés et confirmations de commande','التقييمات والمتابعات':'Avis et abonnements','تنبيهات الدفع':'Alertes de paiement','تنبيهات النظام':'Alertes système','وضع "عدم الإزعاج"':'Mode « Ne pas déranger »','أمس':'Hier','الآن':'Maintenant','الكل':'Tous','قيد الانتظار':'En attente','قيد الشحن':'En livraison','تم الاستلام':'Reçu','مكتمل':'Terminé','نفد المخزون':'Rupture de stock','ملغاة':'Annulée','غير متوفر':'Indisponible','متاح':'Disponible','قريباً':'Bientôt','تأكيد الاختيار':'Confirmer le choix','البلد':'Pays','تونس':'Tunisie','المغرب':'Maroc','ليبيا':'Libye','دينار تونسي':'Dinar tunisien','درهم مغربي':'Dirham marocain','دينار ليبي':'Dinar libyen','دينار جزائري':'Dinar algérien','سياسة ملفات تعريف الارتباط':'Politique relative aux cookies','سياسة الخصوصية':'Politique de confidentialité','شروط الاستخدام':'Conditions d’utilisation','تتبع الطلبية':'Suivre la commande','تأكيد استلام الطلب':'Confirmer la réception','إرسال التقييم':'Envoyer l’avis','تقييم الطلب':'Évaluer la commande','مستورد / تاجر':'Importateur / vendeur','الاسم الكامل':'Nom complet','رقم الهاتف':'Numéro de téléphone','الولاية':'Wilaya','البريد الإلكتروني':'E-mail','كلمة السر':'Mot de passe','أدخل البريد الإلكتروني':'Saisissez l’e-mail','أدخل كلمة السر':'Saisissez le mot de passe','أعد إدخال كلمة السر':'Confirmez le mot de passe','تسجيل الدخول مطلوب':'Connexion requise','حذف الحساب نهائيًا':'Supprimer définitivement le compte','متجر Kilix':'Boutique Kilix','متاجر متنوعة':'Boutiques variées','توريد مباشر':'Approvisionnement direct','تواصل مباشر مع الموردين':'Communication directe avec les fournisseurs','شحن موثوق':'Livraison fiable','أمان المعاملات':'Sécurité des transactions','منتج متاح':'Produit disponible','تاجر نشط':'Vendeur actif','شركة شحن':'Société de livraison','تاجر مسجل':'Vendeur enregistré','مكتب التوصيل':'Bureau de livraison','المنزل':'Domicile','البيت':'Domicile','مكتب':'Bureau','قطعة':'pièce','المحادثة':'Discussion','اكتب رسالة...':'Écrivez un message...','البحث في الرسائل...':'Rechercher dans les messages...','حذف المحادثة':'Supprimer la discussion','هل أنت متأكد؟':'Êtes-vous sûr ?','يناير':'Janvier','فبراير':'Février','مارس':'Mars','أبريل':'Avril','ماي':'Mai','جوان':'Juin','جويلية':'Juillet','أوت':'Août','سبتمبر':'Septembre','أكتوبر':'Octobre','نوفمبر':'Novembre','ديسمبر':'Décembre','جاري المعالجة...':'Traitement...','طلباتي':'Mes commandes','طلبات مكتملة':'Commandes terminées','إجمالي المشتريات':'Total des achats','توفير إجمالي':'Économies totales','ادعُ تاجراً واربح!':'Invitez un vendeur et gagnez !','شارك رابطك واحصل على خصومات':'Partagez votre lien et obtenez des réductions',
  '\n⚠️ تم إنشاء المتجر، لكن تعذر رفع صورة المتجر. يمكنك المحاولة لاحقاً.':'\n⚠️ Boutique créée, mais l’image de la boutique n’a pas pu être téléversée. Vous pouvez réessayer plus tard.',
  '،':',',
  '؟':'?',
  'تم تسجيل الدخول بنجاح':'Connexion réussie',
  'تم إنشاء الحساب بنجاح':'Compte créé avec succès',
  'المتجر غير موجود':'Boutique introuvable',
  'تعذر تحميل المتجر':'Impossible de charger la boutique',
  'حاول مرة أخرى.':'Réessayez.',
  'سجل دخولك لمتابعة المتجر.':'Connectez-vous pour suivre cette boutique.',
  'تعذر تحديث المتابعة':'Impossible de mettre à jour le suivi',
  'سجل دخولك لمراسلة صاحب المتجر.':'Connectez-vous pour contacter le propriétaire de la boutique.',
  'المتجر':'Boutique',
  'تعذر فتح المحادثة':'Impossible d’ouvrir la conversation',
  'تعذر حذف الحساب':'Impossible de supprimer le compte',
  'المستخدم':'Utilisateur',
  'رقم الهاتف غير مضاف':'Numéro de téléphone non ajouté',
  'إدارة منتجاتك وعرضك التجاري':'Gérez vos produits et votre vitrine',
  'فتح رابط السياسة خارج التطبيق':'Ouvrir le lien de la politique hors de l’application',
  'مشكلة في الدفع':'Problème de paiement',
  'الشحن والتتبع':'Expédition et suivi',
  'الحساب':'Compte',
  'أخرى':'Autre',
  'يرجى كتابة رسالتك قبل الإرسال':'Veuillez écrire votre message avant l’envoi',
  'إرسال طلب آخر':'Envoyer une autre demande',
  'العودة للرئيسية':'Retour à l’accueil',
  'اكتب رسالتك هنا...':'Écrivez votre message ici...',
  'ستُبلَّغ فور إطلاق الخدمة في بلدك.':'Vous serez informé dès le lancement du service dans votre pays.',
  'إلكترونيات':'Électronique',
  'نسيج وملابس':'Textiles et vêtements',
  'أدوات منزلية':'Articles ménagers',
  'بناء وإنشاء':'Construction et bâtiment',
  'للنساء':'Femmes',
  'الإلكترونيات':'Électronique',
  'إكسسوارات للأزياء':'Accessoires de mode',
  'المجوهرات':'Bijoux',
  'ملابس و أحذية':'Vêtements et chaussures',
  'ألعاب وهوايات':'Jouets et loisirs',
  'الأمن و الحماية':'Sécurité et protection',
  'الأمهات و الأطفال':'Mères et enfants',
  'الجمال والصحة':'Beauté et santé',
  'للسيارات':'Automobile',
  'أبيض':'Blanc',
  'أسود':'Noir',
  'أزرق':'Bleu',
  'أزرق داكن':'Bleu foncé',
  'رمادي':'Gris',
  'فضي':'Argenté',
  'ذهبي':'Doré',
  'أسود عسكري':'Noir militaire',
  'أحمر':'Rouge',
  'أحمر خمري':'Bordeaux',
  'أخضر':'Vert',
  'أصفر':'Jaune',
  'برتقالي':'Orange',
  'وردي':'Rose',
  'بنفسجي':'Violet',
  'بني':'Marron',
  'بيج':'Beige',
  'فيروزي':'Turquoise',
  'أزرق سماوي':'Bleu ciel',
  'أزياء وملابس':'Mode et vêtements',
  'حواسيب وأجهزة':'Ordinateurs et appareils',
  'هواتف ذكية':'Smartphones',
  'ساعات وإكسسوارات':'Montres et accessoires',
  'أجهزة منزلية':'Appareils ménagers',
  'دج':'DZD',
  'تعذر فتح متجر التطبيقات. يرجى المحاولة مرة أخرى.':'Impossible d’ouvrir la boutique d’applications. Veuillez réessayer.',
  'تعذر فتح متجر التطبيقات.':'Impossible d’ouvrir la boutique d’applications.',
  'غير محدد':'Non spécifié',
  'عام':'Général',
  'تعذّر تحديث الطلبية.':'Impossible de mettre à jour la commande.',
  'يرجى إدخال اسم المنتج والسعر والوصف.':'Veuillez saisir le nom, le prix et la description du produit.',
  'يجب إنشاء المتجر أولاً.':'Vous devez d’abord créer la boutique.',
  'الحد الأدنى والحد الأقصى للطلب غير صالحين.':'Les quantités minimale et maximale de commande sont invalides.',
  'حدث خطأ أثناء نشر المنتج.':'Une erreur est survenue lors de la publication du produit.',
  'تم تعديل المنتج بنجاح!':'Produit modifié avec succès !',
  'تعذّر حفظ التعديلات.':'Impossible d’enregistrer les modifications.',
  'تم حذف المنتج وإزالته من إدارة المخزن والعرض بنجاح.':'Produit supprimé avec succès de l’inventaire et de la vitrine.',
  'تعذّر حذف المنتج.':'Impossible de supprimer le produit.',
  'حدث خطأ أثناء محاولة المشاركة':'Une erreur est survenue lors du partage',
  'خطأ: لم يتمكن من تحديد معرف المتجر.':'Erreur : impossible de déterminer l’identifiant de la boutique.',
  'تم رفع الصورة بنجاح!':'Image téléversée avec succès !',
  'فشل رفع الصورة. يرجى المحاولة مرة أخرى.':'Échec du téléversement de l’image. Veuillez réessayer.',
  'يمكنك رفع فيديو واحد فقط لكل منتج.':'Vous ne pouvez téléverser qu’une seule vidéo par produit.',
  'تم رفع الفيديو بنجاح!':'Vidéo téléversée avec succès !',
  'فشل رفع الفيديو. يرجى المحاولة مرة أخرى.':'Échec du téléversement de la vidéo. Veuillez réessayer.',
  'تعذر اختيار صورة المتجر.':'Impossible de sélectionner l’image de la boutique.',
  'يرجى إدخال اسم المتجر ونوع المنتجات على الأقل.':'Veuillez saisir au moins le nom de la boutique et le type de produits.',
  'خطأ: لم يتم التعرف على المستخدم الحالي.':'Erreur : utilisateur actuel non identifié.',
  'حدث خطأ أثناء الاتصال بقاعدة البيانات.':'Une erreur est survenue lors de la connexion à la base de données.',
  'إدارة الطلبات':'Gestion des commandes',
  'إدارة المخزون':'Gestion de l’inventaire',
  'السجل':'Historique',
  'رفع صورة بروفايل':'Téléverser une photo de profil',
  'أدخل اسم المتجر':'Saisissez le nom de la boutique',
  'مثال: أزياء وملابس، هواتف ذكية...':'Exemple : mode et vêtements, smartphones...',
  'اكتب وصفاً موجزاً عن متجرك...':'Écrivez une brève description de votre boutique...',
  'مثال: 1':'Exemple : 1',
  'مثال: 100':'Exemple : 100',
  'أدخل اسم المنتج':'Saisissez le nom du produit',
  'مثال: 3500':'Exemple : 3500',
  'تفاصيل إضافية عن المنتج...':'Détails supplémentaires sur le produit...',
  'مقاس':'Taille',
  'سعة تخزين':'Capacité de stockage',
  'لون':'Couleur',
  'مثال: 6XL أو 56':'Exemple : 6XL ou 56',
  'مثال: 128GB':'Exemple : 128 Go',
  'مثال: 2TB':'Exemple : 2 To',
  'مثال: تركوازي فاتح':'Exemple : turquoise clair',
  'تم تسجيل الدفعة في سجل المدفوعات.':'Paiement enregistré dans l’historique des paiements.',
  'تعذر تسجيل الدفعة.':'Impossible d’enregistrer le paiement.',
  'غير متوفرة':'Indisponible',
  'لا توجد ملاحظة':'Aucune note',
  'المنتج':'Produit',
  'البحث عن المنتج واختيار المورد':'Rechercher le produit et choisir un fournisseur',
  'ابحث عن المنتج باستخدام الكلمات المفتاحية أو الصورة، واختر المصنع أو المورد المناسب من بين المصانع الصينية الموثقة.':'Recherchez le produit par mots-clés ou par image et choisissez un fabricant ou fournisseur approprié parmi les usines chinoises vérifiées.',
  'إرسال طلب الاستيراد':'Envoyer une demande d’importation',
  'أرسل طلبك عبر المنصة، وسنحوله مباشرة إلى شركة الشحن الشريكة للتواصل مع المصنع والتحقق من السعر والتوفر.':'Envoyez votre demande via la plateforme ; nous la transmettrons directement à la société de transport partenaire pour contacter l’usine et vérifier le prix et la disponibilité.',
  'تأكيد السعر والشحن':'Confirmer le prix et l’expédition',
  'تتواصل شركة الشحن مع المصنع لتأكيد السعر النهائي، وتحدد أفضل طريقة للشحن (بحري أو جوي)، ثم تعرض عليك التكلفة النهائية للموافقة.':'La société de transport contacte l’usine pour confirmer le prix final, choisit le meilleur mode d’expédition (maritime ou aérien), puis vous présente le coût final pour approbation.',
  'الدفع وبدء التنفيذ':'Paiement et exécution',
  'بعد موافقتك على السعر النهائي، يتم الدفع، وتبدأ شركة الشحن في استلام البضاعة من المصنع وتجهيزها للشحن.':'Après votre approbation du prix final, le paiement est effectué et la société de transport récupère les marchandises auprès de l’usine et les prépare pour l’expédition.',
  'الشحن والتخليص الجمركي':'Expédition et dédouanement',
  'تتولى شركة الشحن نقل البضاعة، وإنجاز إجراءات التخليص الجمركي، مع تحديث حالة الطلب في كل مرحلة.':'La société de transport assure le transport des marchandises, les formalités douanières et la mise à jour du statut de la commande à chaque étape.',
  'الاستلام وإغلاق الطلب':'Réception et clôture de la commande',
  'تستلم بضاعتك في الجزائر، وبعد التأكيد على الاستلام يتم إغلاق الطلب بنجاح.':'Vous recevez vos marchandises en Algérie ; après confirmation de la réception, la commande est clôturée avec succès.',
  'ما هي أقل كمية يمكنني استيرادها؟':'Quelle est la quantité minimale que je peux importer ?',
  'كم تستغرق مدة الشحن من الصين للجزائر؟':'Combien de temps prend l’expédition de la Chine vers l’Algérie ?',
  'الشحن الجوي يستغرق عادةً من 7 إلى 12 يوماً، بينما يستغرق الشحن البحري ما بين 35 إلى 45 يوماً للوصول إلى الموانئ الجزائرية الرئيسية.':'Le transport aérien prend généralement 7 à 12 jours, tandis que le transport maritime prend 35 à 45 jours pour atteindre les principaux ports algériens.',
  'هل Kilix تضمن جودة المنتجات؟':'Kilix garantit-elle la qualité des produits ?',
  'نعم، نقدم خدمة فحص الجودة في المصنع قبل الشحن. فريقنا في الصين يقوم بمعاينة البضاعة والتأكد من مطابقتها للمواصفات المتفق عليها قبل إجراء الدفع النهائي للمورد.':'Oui. Nous proposons un contrôle qualité en usine avant l’expédition. Notre équipe en Chine inspecte les marchandises et vérifie leur conformité aux spécifications convenues avant le paiement final au fournisseur.',
  'كيف يتم حساب تكلفة الجمارك؟':'Comment sont calculés les frais de douane ?',
  'تُحسب التكلفة بناءً على تعريفة الجمارك الجزائرية المخصصة لنوع المنتج (Code SH) وقيمة الفاتورة وتكاليف التأمين والشحن. نقدم لك استشارة تقديرية قبل البدء.':'Les coûts sont calculés selon le tarif douanier algérien applicable au type de produit (code SH), la valeur de la facture, l’assurance et le transport. Nous vous fournissons une estimation avant de commencer.',
  'دليل الاستخدام':'Guide d’utilisation',
  'تصنيفات المنتجات':'Catégories de produits',
  'تعذر حفظ الإعدادات':'Impossible d’enregistrer les paramètres',
  'تغيير حالة الطلبية وحالتها':'Changements de statut des commandes',
  'تقييمات المنتجات والمتابعون الجدد':'Avis sur les produits et nouveaux abonnés',
  'تسجيل الدفعات والفواتير':'Enregistrements des paiements et factures',
  'التحديثات العامة للحساب':'Mises à jour générales du compte',
  'كتم الإشعارات في أوقات محددة':'Désactiver les notifications à certaines heures',
  'توصيل آمن':'Livraison sécurisée',
  'دفع عند الاستلام':'Paiement à la livraison',
  'ز.م':'K.M',
  'مستخدم':'Utilisateur',
  'هذا المنتج لم يعد متاحاً من طرف التاجر.':'Ce produit n’est plus disponible auprès du vendeur.',
  'يرجى ملء الاسم، اللقب، رقم الهاتف، والولاية.':'Veuillez renseigner le prénom, le nom, le numéro de téléphone et la wilaya.',
  'يرجى اختيار البلدية وإدخال الشارع لتوصيل المنزل.':'Veuillez choisir la commune et saisir la rue pour la livraison à domicile.',
  'يرجى اختيار البلدية (مكتب التوصيل).':'Veuillez choisir la commune (bureau de livraison).',
  'تعذّر تحديد بيانات المنتج أو المتجر، يرجى المحاولة لاحقاً.':'Impossible de déterminer les données du produit ou de la boutique. Veuillez réessayer plus tard.',
  'تعذّر إرسال الطلب، يرجى المحاولة مرة أخرى.':'Impossible d’envoyer la commande. Veuillez réessayer.',
  'لا تقييم بعد':'Aucun avis pour le moment',
  'المنتج غير متاح حالياً':'Produit actuellement indisponible',
  'اختر الكمية والخيارات':'Choisissez la quantité et les options',
  'تم حذف المنتج من مخزون التاجر ولا يمكن استقبال طلبات جديدة.':'Le produit a été supprimé de l’inventaire du vendeur et ne peut plus recevoir de nouvelles commandes.',
  'أدخل أي تفاصيل إضافية هنا...':'Ajoutez ici tout détail supplémentaire...',
  'إنشاء طلبية':'Créer une commande',
  'أدخل الاسم واللقب':'Saisissez le prénom et le nom',
  'اختر الولاية (69 ولاية)':'Choisissez la wilaya (69 wilayas)',
  'اختر البلدية التابعة للولاية':'Choisissez la commune de la wilaya',
  'أدخل اسم الشارع أو الحي ورقم المنزل':'Saisissez le nom de la rue ou du quartier et le numéro de maison',
  'شحن امن ودفع عند الاستلام':'Livraison sécurisée et paiement à la livraison',
  'معاملا امنة وتوثيق كامل للطلبات':'Transactions sécurisées et vérification complète des commandes',
  'د.ت':'TND',
  'د.م':'MAD',
  'د.ل':'LYD',
  'حقوق المحتوى':'Droits sur le contenu',
  'ملغى':'Annulé',
  'الطلبية':'Commande',
  'تعذّر إرسال الرسالة':'Impossible d’envoyer le message',
  'تعذّر الإرسال':'Échec de l’envoi',
  'لم تُرسَل رسالتك، يرجى المحاولة مرة أخرى.':'Votre message n’a pas été envoyé. Veuillez réessayer.',
  'تم إلغاء تثبيت المحادثة':'Conversation désépinglée',
  'تم تثبيت المحادثة':'Conversation épinglée',
  'تعذّر حذف المحادثة':'Impossible de supprimer la conversation',
  'تعذر حذف المحادثة':'Impossible de supprimer la conversation',
  'تعذر تأكيد الاستلام':'Impossible de confirmer la réception',
  'يرجى المحاولة مرة أخرى.':'Veuillez réessayer.',
  'ابحث في طلباتك':'Rechercher dans vos commandes',
  'إجمالي الدعوات':'Total des invitations',
  'إحالات ناجحة':'Parrainages réussis',
  'إحالات معلّقة':'Parrainages en attente',
  'إجمالي المكافآت':'Total des récompenses',
  'تعذر إرسال التقييم':'Impossible d’envoyer l’avis',
  'طلبك':'Votre commande',
  'اكتب تعليقك عن المنتج وتجربة الشراء...':'Écrivez votre commentaire sur le produit et votre expérience d’achat...',
  'يرجى تعبئة جميع الحقول':'Veuillez remplir tous les champs',
  'البريد الإلكتروني غير صحيح':'Adresse e-mail invalide',
  'كلمة المرور خاطئة':'Mot de passe incorrect',
  'البريد الإلكتروني أو كلمة المرور غير صحيحة':'Adresse e-mail ou mot de passe incorrect',
  'حدث خطأ أثناء تسجيل الدخول، يرجى المحاولة لاحقاً':'Une erreur est survenue lors de la connexion. Veuillez réessayer plus tard',
  'يرجى تعبئة جميع الحقول المطلوبة':'Veuillez remplir tous les champs obligatoires',
  'كلمتا المرور غير متطابقَتين':'Les mots de passe ne correspondent pas',
  'كلمة السر يجب أن تكون 6 أحرف على الأقل':'Le mot de passe doit comporter au moins 6 caractères',
  'هذا البريد الإلكتروني مسجل مسبقاً أو غير صالح':'Cette adresse e-mail est déjà enregistrée ou invalide',
  'حدث خطأ أثناء إنشاء الحساب، يرجى المحاولة لاحقاً':'Une erreur est survenue lors de la création du compte. Veuillez réessayer plus tard',
  'المتابعة أو':'Continuer avec',
  'أدخل الاسم':'Saisissez le prénom',
  'أدخل اللقب':'Saisissez le nom',
  'أدخل رقم الهاتف':'Saisissez le numéro de téléphone',
  'أدخل كلمة السر (6 أحرف على الأقل)':'Saisissez un mot de passe (au moins 6 caractères)',
  'تم إرسال رمز التحقق.':'Code de vérification envoyé.',
  'يرجى إدخال رمز التحقق.':'Veuillez saisir le code de vérification.',
  'يرجى إدخال رمز التحقق كاملاً.':'Veuillez saisir le code de vérification complet.',
  'انتهت صلاحية رمز التحقق.':'Le code de vérification a expiré.',
  'تم إنشاء الحساب بنجاح.':'Compte créé avec succès.',
  'تأكيد والدخول':'Confirmer et se connecter',
  'صلاحية الوصول مرفوضة':'Autorisation refusée',
  'فتح الإعدادات':'Ouvrir les paramètres',
  'صلاحية الكاميرا مرفوضة':'Autorisation de la caméra refusée',
  'تعذّر تجهيز الصورة للبحث':'Impossible de préparer l’image pour la recherche',
  'الأبعاد الأصلية':'Dimensions originales',
  'مربع':'Carré',
  'قياسي':'Standard',
  'عريض':'Large',
  'أصلي':'Original',
  'مثال: حقيبة سوداء جلدية':'Exemple : sac en cuir noir',
  'رفع الصورة':'Téléverser l’image',
  'تحليل المحتوى':'Analyse du contenu',
  'استخراج النتائج':'Extraction des résultats',
  'ابحث عن منتجات...':'Rechercher des produits...',
  'ابحث عن منتجات، موردين...':'Rechercher des produits, fournisseurs...',
  'جارٍ تحميل المزيد...':'Chargement de plus de résultats...',
  'اسحب للأسفل لرؤية المزيد':'Tirez vers le bas pour voir plus',
  'لإتمام طلبك بأمان وتتبعه لاحقاً':'Pour finaliser votre commande en toute sécurité et la suivre plus tard',
  'لحفظ سلتك وإدارة مشترياتك بسهولة':'Pour enregistrer votre panier et gérer facilement vos achats',
  'مجموعات الاختيار':'Groupes d’options',
  'مقلوبة الترتيب':'Ordre inversé',
  'يرجى إدخال البريد الإلكتروني.':'Veuillez saisir votre adresse e-mail.',
  'يرجى إدخال بريد إلكتروني صحيح.':'Veuillez saisir une adresse e-mail valide.',
  'يرجى إدخال كلمة سر لا تقل عن 6 أحرف.':'Veuillez saisir un mot de passe d’au moins 6 caractères.',
  'سيتم حذف حسابك نهائيًا، بما في ذلك بريدك الإلكتروني وبياناتك الشخصية ومتجرك ومنتجاته وصوره وفيديوهاته والبيانات المرتبطة بحسابك. لا يمكن التراجع عن هذه العملية.':'Votre compte sera définitivement supprimé, y compris votre adresse e-mail, vos données personnelles, votre boutique, ses produits, images, vidéos et les données associées. Cette action est irréversible.',
  'طلبية جديدة':'Nouvelle commande','تم تأكيد الطلب':'Commande confirmée','تم استلام الطلب':'Commande reçue','اكتملت الطلبية':'Commande terminée','رسالة جديدة':'Nouveau message','تقييم جديد':'Nouvel avis','متابع جديد':'Nouvel abonné','الدفع المستحق':'Paiement dû','وصلت طلبية جديدة إلى متجرك':'Une nouvelle commande est arrivée dans votre boutique','تم تأكيد طلبك من طرف التاجر وأصبح قيد الشحن':'Votre commande a été confirmée par le vendeur et est maintenant en livraison','نعتذر، المنتج المطلوب غير متوفر حالياً':'Désolé, le produit demandé est actuellement indisponible','أكد المشتري استلام الطلب':'L’acheteur a confirmé la réception de la commande','تم إكمال الطلب بعد تقييم المشتري':'La commande a été finalisée après l’avis de l’acheteur','لديك رسالة جديدة في المحادثات':'Vous avez un nouveau message dans vos discussions','تمت إضافة تقييم جديد لمنتجك':'Un nouvel avis a été ajouté à votre produit','قام مستخدم بمتابعة متجرك':'Un utilisateur a suivi votre boutique','وصلت رسوم الاشتراك إلى 500 دج أو أكثر؛ يرجى تسوية الرصيد المستحق.':'Vos frais d’abonnement ont atteint 500 DZD ou plus ; veuillez régler le solde dû.','تم تسجيل الدفعة':'Paiement enregistré','غير مقروء':'non lu','قراءة الكل':'Tout marquer comme lu','لا توجد إشعارات':'Aucune notification','ستظهر هنا إشعارات طلباتك ومراسلاتك':'Les notifications de vos commandes et messages apparaîtront ici','إعدادات الإشعارات':'Paramètres des notifications','إشعارات':'Notifications',
  'متابع':'Suivi',
  'منتج':'Produit',
  'تقييم':'Avis',
  'مراسلة':'Contacter',
  'منتجات المتجر':'Produits de la boutique',
  'لا توجد منتجات منشورة حالياً.':'Aucun produit publié pour le moment.',
  'تم إرسال طلبك':'Votre demande a été envoyée',
  'لقد استلمنا رسالتك وسيتواصل معك فريق الدعم قريباً.':'Nous avons reçu votre message et notre équipe d’assistance vous contactera bientôt.',
  'قنوات التواصل':'Canaux de contact',
  'اتصل بنا':'Contactez-nous',
  'دردشة مباشرة':'Chat en direct',
  'متاح ٨ص – ١٠م':'Disponible de 8 h à 22 h',
  'أرسل طلب دعم':'Envoyer une demande d’assistance',
  'سنرد عليك خلال ٢٤ ساعة.':'Nous vous répondrons sous 24 heures.',
  'الموضوع':'Sujet',
  'رسالتك':'Votre message',
  'متاح الآن':'Disponible maintenant',
  'اختيار بلد غير متاح حالياً سيضعك في قائمة الانتظار. ستُبلّغ فور إطلاق الخدمة في بلدك.':'Le choix d’un pays actuellement indisponible vous ajoutera à la liste d’attente. Vous serez informé dès le lancement du service dans votre pays.',
  'إنشاء متجرك الجديد':'Créez votre nouvelle boutique',
  'أدخل تفاصيل متجرك أدناه للبدء في إدارة الطلبات والمخزون بكل احترافية.':'Saisissez les informations de votre boutique ci-dessous pour commencer à gérer vos commandes et votre inventaire avec professionnalisme.',
  'بيانات المتجر الأساسية':'Informations de base de la boutique',
  'صورة بروفايل المتجر (اختيارية)':'Photo de profil de la boutique (facultative)',
  'ستظهر هذه الصورة للمستخدمين في صفحة المنتج وصفحة تفاصيل المتجر.':'Cette image sera visible par les utilisateurs sur la page du produit et la page de détails de la boutique.',
  'اسم المتجر':'Nom de la boutique',
  'نوع المنتجات التي يبيعها المتجر':'Types de produits vendus par la boutique',
  'نوع النشاط التجاري':'Type d’activité commerciale',
  'بائع جملة':'Grossiste',
  'مصنع':'Fabricant',
  'وصف للمتجر':'Description de la boutique',
  'لا توجد طلبات حالياً':'Aucune commande pour le moment',
  'تأكيد':'Confirmer',
  'نفد':'Rupture de stock',
  'التفاصيل':'Détails',
  'لا توجد منتجات حالياً':'Aucun produit pour le moment',
  'تعديل':'Modifier',
  'إضافة منتج':'Ajouter un produit',
  'اضغط على أي معاملة لعرض التفاصيل الكاملة.':'Appuyez sur une transaction pour afficher tous les détails.',
  'لا توجد معاملات حالياً':'Aucune transaction pour le moment',
  'عرض التفاصيل':'Voir les détails',
  'تعديل بيانات المنتج':'Modifier les informations du produit',
  'نموذج المنتج':'Formulaire du produit',
  'السعر الأساسي (دج)':'Prix de base (DZD)',
  'تصنيف المنتج':'Catégorie du produit',
  'خيارات الرام (RAM)':'Options de RAM',
  'إضافة RAM مخصص':'Ajouter une RAM personnalisée',
  'سعات التخزين':'Capacités de stockage',
  'إضافة تخزين مخصص':'Ajouter un stockage personnalisé',
  'الأحجام المتوفرة':'Tailles disponibles',
  'إضافة مقاس':'Ajouter une taille',
  'الألوان المتوفرة':'Couleurs disponibles',
  'إضافة لون':'Ajouter une couleur',
  'الحد الأدنى للطلب':'Quantité minimale de commande',
  'الحد الأقصى للطلب':'Quantité maximale de commande',
  'رفع الصور والفيديوهات':'Téléverser des images et des vidéos',
  'الفيديوهات — متاح قريبًا':'Vidéos — bientôt disponibles',
  'حفظ التعديلات':'Enregistrer les modifications',
  'إضافة منتج جديد':'Ajouter un nouveau produit',
  'وصف المنتج (اختياري)':'Description du produit (facultative)',
  'إضافة':'Ajouter',
  'كيفية حساب الرسوم':'Comment les frais sont calculés',
  'تُحسب الرسوم بنسبة 0.3% من قيمة المنتجات التي تم بيعها فقط.':'Les frais sont calculés à hauteur de 0,3 % de la valeur des produits vendus uniquement.',
  'طريقة الحساب':'Méthode de calcul',
  'قيمة المنتجات × 0.003 = الرسوم':'Valeur des produits × 0,003 = frais',
  'مثال 1':'Exemple 1',
  '30,000 سنتيم':'30 000 centimes',
  'مثال 2':'Exemple 2',
  '60,000 سنتيم':'60 000 centimes',
  'مثال 3':'Exemple 3',
  '300,000 سنتيم':'300 000 centimes',
  'إغلاق':'Fermer',
  'قم بتحديث التطبيق':'Mettez à jour l’application',
  'قم بتحديث التطبيق للاستمرار في الاستفادة من الخدمات وإتمام الدفع.':'Mettez à jour l’application pour continuer à utiliser les services et effectuer les paiements.',
  'تحديث التطبيق':'Mettre à jour l’application',
  'اختر نوع جهازك':'Choisissez votre appareil',
  'سيتم نقلك مباشرة إلى صفحة Kilix في متجر التطبيقات.':'Vous serez redirigé directement vers la page Kilix dans la boutique d’applications.',
  'دفع الرصيد المستحق':'Payer le solde dû',
  'اختر وسيلة الدفع المناسبة لإتمام التسوية.':'Choisissez le mode de paiement approprié pour régler le solde.',
  'بريدي موب (BaridiMob)':'BaridiMob',
  'البطاقة الذهبية (Dahabia)':'Carte Dahabia',
  'حذف المنتج؟':'Supprimer le produit ?',
  'هل أنت متأكد من رغبتك في حذف هذا المنتج؟ لا يمكن التراجع عن هذا الإجراء.':'Voulez-vous vraiment supprimer ce produit ? Cette action est irréversible.',
  'تمت إضافة المنتج بنجاح':'Produit ajouté avec succès',
  'أصبح منتجك الجديد متاحاً الآن في المخزون وجاهزاً لاستقبال الطلبات.':'Votre nouveau produit est maintenant disponible dans l’inventaire et prêt à recevoir des commandes.',
  'حسناً':'OK',
  'بدون خيارات إضافية':'Aucune option supplémentaire',
  'لا توجد تفاصيل مجموعات محفوظة لهذه الطلبية.':'Aucun détail de groupe enregistré pour cette commande.',
  'كيف تستورد من الصين؟':'Comment importer depuis la Chine ?',
  'نحن هنا لتبسيط رحلة استيرادك. اتبع هذه الخطوات الست للوصول بمنتجاتك من المصنع في الصين إلى مستودعك في الجزائر.':'Nous sommes là pour simplifier votre parcours d’importation. Suivez ces six étapes pour acheminer vos produits de l’usine en Chine jusqu’à votre entrepôt en Algérie.',
  'أسئلة شائعة':'Questions fréquentes',
  'عندك سؤال؟':'Une question ?',
  'فريق الدعم الفني لدينا متاح للإجابة على جميع استفساراتكم':'Notre équipe d’assistance technique est disponible pour répondre à toutes vos questions.',
  'من 8:00 صباحاً حتى 10:00 مساءً':'De 8 h à 22 h',
  'تواصل معنا':'Contactez-nous',
  '© 2026 Kilix DZ Sourcing Pass. جميع الحقوق محفوظة.':'© 2026 Kilix DZ Sourcing Pass. Tous droits réservés.',
  'شروط الخدمة':'Conditions d’utilisation',
  'تفعيل كافة الإشعارات':'Activer toutes les notifications',
  'تحكم في جميع تنبيهات التطبيق بضغطة واحدة':'Contrôlez toutes les notifications de l’application en un seul geste',
  'الطلبات والشحن':'Commandes et expédition',
  'المحادثات والتقييمات':'Conversations et avis',
  'ساعات الهدوء':'Heures silencieuses',
  'من الساعة':'De',
  '10:00 م':'22:00',
  'إلى الساعة':'À',
  '08:00 ص':'08:00',
  'لا توجد محادثات بعد':'Aucune conversation pour le moment',
  'خيارات المنتج':'Options du produit',
  'من يوم إلى 4 أيام':'De 1 à 4 jours',
  'مدة الشحن :':'Durée d’expédition :',
  'تقييمات العملاء':'Avis des clients',
  'لا توجد تقييمات بعد لهذا المنتج':'Aucun avis pour ce produit pour le moment',
  'شراء مؤكد ✓':'Achat vérifié ✓',
  'منتجات قد تعجبك أيضاً':'Produits susceptibles de vous plaire',
  'السلة':'Panier',
  'تخصيص الطلب':'Personnaliser la commande',
  'ملاحظات إضافية':'Notes supplémentaires',
  'يرجى إكمال كل الخيارات الإلزامية في كل مجموعة والتأكد من توفرها':'Veuillez compléter toutes les options obligatoires de chaque groupe et vérifier leur disponibilité.',
  'معلومات الشحن والتوصيل':'Informations d’expédition et de livraison',
  'الاسم واللقب':'Prénom et nom',
  'طريقة التوصيل':'Mode de livraison',
  'توصيل للمنزل':'Livraison à domicile',
  'توصيل لمكتب التوصيل':'Livraison au bureau de livraison',
  'البلدية':'Commune',
  'الشارع / الحي':'Rue / quartier',
  'تم إنشاء طلبية بنجاح!':'Commande créée avec succès !',
  'تم تسجيل طلبك ومعالجته بنجاح، سنتواصل معك قريباً لتأكيد التوصيل.':'Votre commande a été enregistrée et traitée avec succès. Nous vous contacterons bientôt pour confirmer la livraison.',
  'الإصدار 1.2.0':'Version 1.2.0',
  'وسيط ذكي يربط التجار الجملة بتجار التجزئة — بدون وسطاء، بدون تعقيد.':'Un intermédiaire intelligent qui relie les grossistes aux détaillants — sans intermédiaires, sans complexité.',
  'لماذا Kilix؟':'Pourquoi Kilix ?',
  '© 2026 Kilix · الجزائر':'© 2026 Kilix · Algérie',
  'اختر العملة المفضلة':'Choisissez votre devise préférée',
  'تقدم الطلبية':'Progression de la commande',
  'الحالة الفعلية المسجلة في الطلبية':'Statut réel enregistré pour la commande',
  'رقم الطلب':'Numéro de commande',
  'طلبية واحدة':'Une commande',
  'الحالة المسجلة':'Statut enregistré',
  'لا توجد طلبية للتتبع':'Aucune commande à suivre',
  'افتح التتبع من سجل الطلبات لعرض الحالة الفعلية.':'Ouvrez le suivi depuis l’historique des commandes pour voir le statut réel.',
  'تم ترك تعليقك بنجاح.':'Votre avis a été envoyé avec succès.',
  'سلتك فارغة':'Votre panier est vide',
  'أضف منتجات من الصفحة الرئيسية لتظهر هنا':'Ajoutez des produits depuis la page d’accueil pour les voir ici',
  'تصفح المنتجات':'Parcourir les produits',
  'سلة التسوق':'Panier',
  'تحديد الكل':'Tout sélectionner',
  'قراءة الكل':'Tout marquer comme lu',
  'لا توجد إشعارات':'Aucune notification',
  'ستظهر هنا إشعارات طلباتك ومراسلاتك':'Les notifications de vos commandes et messages apparaîtront ici',
  'تثبيت المحادثة':'Épingler la conversation',
  'مشاركة المحادثة':'Partager la conversation',
  'جارٍ تحميل طلباتك...':'Chargement de vos commandes...',
  'لا توجد طلبات في هذا القسم':'Aucune commande dans cette section',
  'تاريخ الطلب':'Date de commande',
  'فتح سياسة الخصوصية العامة':'Ouvrir la politique générale de confidentialité',
  'طلب حذف الحساب والبيانات':'Demander la suppression du compte et des données',
  'لا توجد عروض إحالة متاحة حاليًا.':'Aucune offre de parrainage n’est disponible actuellement.',
  'تحديث':'Actualiser',
  'عروض الإحالة':'Offres de parrainage',
  'ادعُ أصدقاءك واكسب مكافآت حصرية':'Invitez vos amis et gagnez des récompenses exclusives',
  'إحصائياتي في الإحالة':'Mes statistiques de parrainage',
  'رابط الإحالة الخاص بك':'Votre lien de parrainage',
  'الكود':'Code',
  'الرابط':'Lien',
  'نسخ الرابط':'Copier le lien',
  'نسخ الكود':'Copier le code',
  'سجل الإحالات':'Historique des parrainages',
  'نظام الإحالات غير مفعل في مخطط قاعدة البيانات الحالي.':'Le système de parrainage n’est pas activé dans le schéma actuel de la base de données.',
  'تم تسليم طلبك بنجاح. شاركنا رأيك لمساعدتنا على التحسّن.':'Votre commande a été livrée avec succès. Partagez votre avis pour nous aider à nous améliorer.',
  'ما تقييمك للطلب؟':'Comment évaluez-vous la commande ?',
  'أضف تعليقك (اختياري)':'Ajoutez votre commentaire (facultatif)',
  'احصل على كوبون خصم بقيمة 500 دج عند ترك تعليق.':'Obtenez un coupon de réduction de 500 DZD en laissant un avis.',
  'إنشاء حساب':'Créer un compte',
  'تسجيل الدخول':'Se connecter',
  'المتابعة كضيف':'Continuer en tant qu’invité',
  'التسوق':'Shopping',
  'تصفح واشتري':'Parcourez et achetez',
  'أنشئ متجرك':'Créez votre boutique',
  'آمن':'Sécurisé',
  'مشفر ومحمي':'Chiffré et protégé',
  'دخول':'Connexion',
  'ليس لديك حساب؟ اشترك الآن':'Vous n’avez pas de compte ? Inscrivez-vous maintenant',
  'إنشاء حساب جديد':'Créer un nouveau compte',
  'الاسم':'Prénom',
  'اللقب':'Nom',
  'تأكيد كلمة السر':'Confirmer le mot de passe',
  'رجوع':'Retour',
  'تأكيد رمز التحقق':'Vérifier le code',
  'إعادة إرسال الرمز':'Renvoyer le code',
  'البحث بالصورة':'Recherche par image',
  'بحث':'Rechercher',
  'حدد أبعاد الصورة قبل البحث':'Définissez les dimensions de l’image avant la recherche',
  'أبعاد البحث':'Dimensions de recherche',
  'ما الذي تبحث عنه تحديدًا؟':'Que recherchez-vous exactement ?',
  'اختياري: اكتب نوع المنتج أو اللون أو أي تفصيل تريد التركيز عليه.':'Facultatif : indiquez le type de produit, la couleur ou tout détail sur lequel vous souhaitez vous concentrer.',
  'بحث بهذه الصورة':'Rechercher avec cette image',
  'ابحث بصورة منتج':'Rechercher par image de produit',
  'التقط صورة أو اختر من معرضك للعثور على منتجات مشابهة في كتالوج Kilix.':'Prenez une photo ou choisissez-en une dans votre galerie pour trouver des produits similaires dans le catalogue Kilix.',
  'الصلاحية مرفوضة':'Autorisation refusée',
  'يتطلب البحث بالصورة الوصول إلى المعرض أو الكاميرا. افتح إعدادات الجهاز لتفعيل الصلاحية.':'La recherche par image nécessite l’accès à la galerie ou à la caméra. Ouvrez les paramètres de l’appareil pour autoriser l’accès.',
  'معرض الصور':'Galerie photos',
  'اختر من ألبوماتك':'Choisissez dans vos albums',
  'الكاميرا':'Caméra',
  'التقط صورة جديدة':'Prenez une nouvelle photo',
  'للحصول على أفضل نتائج، استخدم صورة واضحة للمنتج على خلفية بيضاء أو مُحايدة.':'Pour de meilleurs résultats, utilisez une photo claire du produit sur un fond blanc ou neutre.',
  'جاري تحليل الصورة...':'Analyse de l’image...',
  'نبحث عن المنتجات المشابهة في الكتالوج':'Recherche de produits similaires dans le catalogue',
  'منتجات مشابهة':'Produits similaires',
  'جرّب صورة أخرى':'Essayez une autre image',
  'لا توجد منتجات مشابهة':'Aucun produit similaire trouvé',
  'لم نتمكن من العثور على منتجات مشابهة لهذه الصورة. جرّب صورة أكثر وضوحاً أو زاوية مختلفة.':'Nous n’avons pas trouvé de produits similaires pour cette image. Essayez une photo plus claire ou un angle différent.',
  'تعذّر تحليل الصورة':'Impossible d’analyser l’image',
  'حدث خطأ أثناء معالجة الصورة. تأكد من الاتصال بالإنترنت وحاول مجدداً.':'Une erreur est survenue lors du traitement de l’image. Vérifiez votre connexion Internet et réessayez.',
  'إعادة المحاولة':'Réessayer',
  'ابحث عن منتجات':'Rechercher des produits',
  'ابدأ بكتابة ما تبحث عنه للعثور على منتجات':'Commencez à saisir ce que vous recherchez pour trouver des produits',
  'لم نجد نتائج':'Aucun résultat trouvé',
  'جرّب كلمات بحث مختلفة':'Essayez d’autres termes de recherche',
  'معاملات والمحادثات محمية داخل التطبيق':'Les transactions et les conversations sont protégées dans l’application',
  'جارٍ تحميل المنتجات...':'Chargement des produits...',
  'لا توجد منتجات في هذا التصنيف حالياً':'Aucun produit dans cette catégorie actuellement',
  'أنشئ حساباً للمتابعة':'Créez un compte pour continuer',
  'متابعة التصفح':'Continuer la navigation',
  'مطلوب':'Obligatoire',
  'مكتملة':'Terminée',
  'غير مكتملة':'Incomplète',
  'هذا المنتج لا يحتوي على خيارات إضافية':'Ce produit ne contient aucune option supplémentaire',
  'هذه التوليفة غير متوفرة حالياً، جرّب خياراً آخر':'Cette combinaison est actuellement indisponible, essayez une autre option',
  'الكمية':'Quantité',
  'سعر هذه المجموعة':'Prix de ce groupe',
  'حدث خطأ غير متوقع':'Une erreur inattendue est survenue',
  'للأسف، حدث شيء ما غير صحيح في التطبيق. يرجى المحاولة مرة أخرى.':'Malheureusement, un problème est survenu dans l’application. Veuillez réessayer.',
  '📋 تفاصيل الخطأ:':'📋 Détails de l’erreur :',
  '🔄 إعادة محاولة':'🔄 Réessayer',
  'العودة':'Retour',
  'إذا استمرت المشكلة، يرجى الاتصال بفريق الدعم.':'Si le problème persiste, veuillez contacter l’assistance.',
  'اختر أحد الخيارات التالية للاطلاع على التفاصيل':'Choisissez l’une des options suivantes pour consulter les détails',
  'إضافة مجموعة أخرى':'Ajouter un autre groupe',
  'عدد المجموعات':'Nombre de groupes',
  'إجمالي الكمية':'Quantité totale',
  'السعر الإجمالي':'Prix total',
  'تسجيل الدخول أو إنشاء حساب':'Connectez-vous ou créez un compte',
  'أدخل بريدك الإلكتروني للمتابعة':'Saisissez votre e-mail pour continuer',

  'وسيط ذكي يربط التجار الجملة بتجار التجزئة  — بدون وسطاء، بدون تعقيد.':'Une plateforme intelligente reliant grossistes et détaillants — sans intermédiaires ni complications.',
  'السعر:':'Prix :',
  'قيمة المنتجات المباعة:':'Valeur des produits vendus :',
  'أي':'Tout',
  'الرسوم:':'Frais :',
  'يتم احتساب الرسوم بنفس النسبة دائمًا:':'Les frais sont toujours calculés au même taux :',
  'من قيمة المنتجات المباعة.':'de la valeur des produits vendus.',
  'الاسم:':'Nom :',
  'رقم الهاتف:':'Numéro de téléphone :',
  'الولاية:':'Wilaya :',
  'البلدية:':'Commune :',
  'طريقة التوصيل:':'Mode de livraison :',
  'عنوان البيت:':'Adresse du domicile :',
  'نقطة التسليم:':'Point de livraison :',
  'مكتب التوصيل في البلدية المحددة':'Bureau de livraison dans la commune sélectionnée',
  'الملاحظة:':'Remarque :',
  'الحالة:':'Statut :',
  'المجموع:':'Total :',
  'إجمالي الكمية:':'Quantité totale :',
  'التسوق':'Achats',
};

const LanguageContext = React.createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = React.useState('ar');
  const [isLanguageReady, setIsLanguageReady] = React.useState(false);
  const [hasSavedLanguage, setHasSavedLanguage] = React.useState(false);

  React.useEffect(() => {
    AsyncStorage.getItem(STORAGE_KEY).then((saved) => {
      if (saved && LANGUAGES[saved]) {
        activeLanguage = saved;
        setLanguageState(saved);
        setHasSavedLanguage(true);
      }
      setIsLanguageReady(true);
    }).catch(() => {
      setIsLanguageReady(true);
    });
  }, []);

  const setLanguage = React.useCallback(async (next) => {
    if (!LANGUAGES[next]) return;
    activeLanguage = next;
    setLanguageState(next);
    try {
      await AsyncStorage.setItem(STORAGE_KEY, next);
      setHasSavedLanguage(true);
    } catch (_) {}
  }, []);

  const t = React.useCallback((value) => {
    if (typeof value !== 'string' || language === 'ar') return value;
    const table = language === 'en' ? EN : FR;
    return Object.prototype.hasOwnProperty.call(table, value) ? table[value] : translateKnownUiTemplate(value, language);
  }, [language]);

  const value = React.useMemo(() => ({ language, setLanguage, t, languages: LANGUAGES, isLanguageReady, hasSavedLanguage }), [language, setLanguage, t, isLanguageReady, hasSavedLanguage]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = React.useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used inside LanguageProvider');
  return context;
}

function translateKnownUiTemplate(value, language) {
  if (typeof value !== 'string' || language === 'ar') return value;
  const templates = [
    [/^تم تسجيل دفعة بقيمة (.+) دج بنجاح$/, n => language === 'fr' ? `Paiement de ${n} DZD enregistré avec succès` : `Payment of ${n} DZD recorded successfully`],
    [/^تم تسجيل الدفعة في سجل المدفوعات\.$/, () => language === 'fr' ? 'Paiement enregistré dans l’historique des paiements.' : 'Payment recorded in the payment history.'],
    [/^تم بيع (.+) وحدة$/, n => language === 'fr' ? `${n} unités vendues` : `${n} units sold`],
    [/^✅ تم إنشاء متجرك بنجاح!\n📌 معرف البحث: (.+)$/, n => language === 'fr' ? `✅ Votre boutique a été créée avec succès !\n📌 Identifiant de recherche : ${n}` : `✅ Your store was created successfully!\n📌 Search ID: ${n}`],
    [/^%(.+) خصم$/, n => language === 'fr' ? `${n} % de réduction` : `${n}% discount`],
    [/^خصم (.+)٪$/, n => language === 'fr' ? `Remise de ${n} %` : `${n}% discount`],
    [/^تخفيض · -(.+)% الآن$/, n => language === 'fr' ? `Réduction · -${n} % maintenant` : `Sale · -${n}% now`],
    [/^صورة (\d+)$/, n => language === 'fr' ? `Image ${n}` : `Image ${n}`],
    [/^الصورة\s*(\d+)\s*من\s*(\d+)$/, (a,b) => language === 'fr' ? `Image ${a} sur ${b}` : `Image ${a} of ${b}`],
    [/^فيديو (\d+)$/, n => language === 'fr' ? `Vidéo ${n}` : `Video ${n}`],
    [/^متجر$/, () => language === 'fr' ? 'Boutique' : 'Store'],
    [/^إدارة ومتابعة الطلبات \((.+)\)$/, n => language === 'fr' ? `Gérer et suivre les commandes (${n})` : `Manage and track orders (${n})`],
    [/^إدارة المخزون والمنتجات \((.+)\)$/, n => language === 'fr' ? `Gestion du stock et des produits (${n})` : `Manage inventory and products (${n})`],
    [/^سجل المعاملات والطلبات \((.+)\)$/, n => language === 'fr' ? `Historique des transactions et commandes (${n})` : `Transaction and order history (${n})`],
    [/^الكمية الإجمالية يجب أن تكون بين (.+) و(.+) وحدة$/, (a,b) => language === 'fr' ? `La quantité totale doit être comprise entre ${a} et ${b} unités` : `Total quantity must be between ${a} and ${b} units`],
    [/^الحد الأدنى (.+) والحد الأقصى (.+) وحدة للطلب$/, (a,b) => language === 'fr' ? `Minimum ${a} et maximum ${b} unités par commande` : `Minimum ${a} and maximum ${b} units per order`],
    [/^الاسم: (.+)$/, n => language === 'fr' ? `Nom : ${n}` : `Name: ${n}`],
    [/^نوع الحساب: (.+)$/, n => {
      const labels = {
        'مستورد / تاجر': ['Importateur / vendeur', 'Importer / seller'],
        'مورّد / مصنّع': ['Fournisseur / fabricant', 'Supplier / manufacturer'],
      };
      const label = labels[n] ? labels[n][language === 'fr' ? 0 : 1] : n;
      return language === 'fr' ? `Type de compte : ${label}` : `Account type: ${label}`;
    }],
    [/^الزبون: (.+)$/, n => language === 'fr' ? `Client : ${n}` : `Customer: ${n}`],
    [/^الهاتف: (.+)$/, n => language === 'fr' ? `Téléphone : ${n}` : `Phone: ${n}`],
    [/^رقم الهاتف: (.+)$/, n => language === 'fr' ? `Numéro de téléphone : ${n}` : `Phone number: ${n}`],
    [/^السعر: (.+)$/, n => language === 'fr' ? `Prix : ${n}` : `Price: ${n}`],
    [/^الولاية: (.+)$/, n => language === 'fr' ? `Wilaya : ${n}` : `State: ${n}`],
    [/^البلدية: (.+)$/, n => language === 'fr' ? `Commune : ${n}` : `Municipality: ${n}`],
    [/^طريقة التوصيل: (.+)$/, n => language === 'fr' ? `Mode de livraison : ${n}` : `Delivery method: ${n}`],
    [/^عنوان البيت: (.+)$/, n => language === 'fr' ? `Adresse du domicile : ${n}` : `Home address: ${n}`],
    [/^الملاحظة: (.+)$/, n => language === 'fr' ? `Remarque : ${n}` : `Note: ${n}`],
    [/^الحالة: (.+)$/, n => language === 'fr' ? `Statut : ${n}` : `Status: ${n}`],
    [/^المجموع: (.+)$/, n => language === 'fr' ? `Total : ${n}` : `Total: ${n}`],
    [/^إجمالي الكمية: (.+)$/, n => language === 'fr' ? `Quantité totale : ${n}` : `Total quantity: ${n}`],
    [/^تم تحديث الطلبية إلى: (.+)$/, n => language === 'fr' ? `Commande mise à jour : ${n}` : `Order updated to: ${n}`],
    [/^تم إضافة كوبون خصم بقيمة (.+) دج إلى حسابك\.$/, n => language === 'fr' ? `Un coupon de réduction de ${n} DZD a été ajouté à votre compte.` : `A discount coupon worth ${n} DZD has been added to your account.`],
    [/^الكمية: (.+) (.+) • (.+) دج$/, (qty, unit, total) => { const units = { 'قطعة': language === 'fr' ? 'pièce' : 'piece', 'وحدة': language === 'fr' ? 'unité' : 'unit' }; return language === 'fr' ? `Quantité : ${qty} ${units[unit] || unit} • ${total} DZD` : `Quantity: ${qty} ${units[unit] || unit} • ${total} DZD`; }],
    [/^الكمية: (.+)$/, n => language === 'fr' ? `Quantité : ${n}` : `Quantity: ${n}`],
    [/^⚠️ حدث هذا الخطأ (.+) مرات$/, n => language === 'fr' ? `⚠️ Cette erreur s’est produite ${n} fois` : `⚠️ This error occurred ${n} times`],
    [/^محادثة مع (.+)$/, n => language === 'fr' ? `Conversation avec ${n}` : `Chat with ${n}`],
    [/^معرفي في Kilix: (.+)$/, n => language === 'fr' ? `Mon identifiant Kilix : ${n}` : `My Kilix ID: ${n}`],
    [/^إضافة (.+) جديد$/, n => {
      const en = { 'مقاس': 'size', 'RAM': 'RAM', 'سعة تخزين': 'storage capacity', 'لون': 'color' }[n] || n;
      const fr = { 'مقاس': 'une taille', 'RAM': 'RAM', 'سعة تخزين': 'une capacité de stockage', 'لون': 'une couleur' }[n] || n;
      return language === 'fr' ? `Ajouter ${fr}` : `Add ${en}`;
    }],
    [/^اليوم، (.+)$/, n => {
      const months = { 'يناير': ['January','janvier'], 'فبراير': ['February','février'], 'مارس': ['March','mars'], 'أبريل': ['April','avril'], 'ماي': ['May','mai'], 'جوان': ['June','juin'], 'يونيو': ['June','juin'], 'جويلية': ['July','juillet'], 'يوليو': ['July','juillet'], 'أوت': ['August','août'], 'أغسطس': ['August','août'], 'سبتمبر': ['September','septembre'], 'أكتوبر': ['October','octobre'], 'نوفمبر': ['November','novembre'], 'ديسمبر': ['December','décembre'] };
      let date = n;
      for (const [ar, names] of Object.entries(months)) date = date.replace(ar, names[language === 'fr' ? 1 : 0]);
      return language === 'fr' ? `Aujourd’hui, ${date}` : `Today, ${date}`;
    }],
    [/^تم تحديد (.+) كبلدك الحالي$/, n => {
      const countries = { 'الجزائر': ['Algeria','Algérie'], 'تونس': ['Tunisia','Tunisie'], 'المغرب': ['Morocco','Maroc'], 'ليبيا': ['Libya','Libye'], 'موريتانيا': ['Mauritania','Mauritanie'], 'الصين': ['China','Chine'], 'الإمارات': ['United Arab Emirates','Émirats arabes unis'], 'السعودية': ['Saudi Arabia','Arabie saoudite'] };
      const country = countries[n] ? countries[n][language === 'fr' ? 1 : 0] : n;
      return language === 'fr' ? `${country} a été défini comme votre pays actuel` : `${country} set as your current country`;
    }],
    [/^تم تسجيلك في قائمة انتظار (.+)$/, n => {
      const countries = { 'الجزائر': ['Algeria','Algérie'], 'تونس': ['Tunisia','Tunisie'], 'المغرب': ['Morocco','Maroc'], 'ليبيا': ['Libya','Libye'], 'موريتانيا': ['Mauritania','Mauritanie'], 'الصين': ['China','Chine'], 'الإمارات': ['United Arab Emirates','Émirats arabes unis'], 'السعودية': ['Saudi Arabia','Arabie saoudite'] };
      const country = countries[n] ? countries[n][language === 'fr' ? 1 : 0] : n;
      return language === 'fr' ? `Vous êtes sur la liste d’attente de ${country}` : `You have been added to the ${country} waiting list`;
    }],
    [/^شاهد هذا المنتج الرائع: (.+)\nالسعر: (.+)$/, (title, price) => language === 'fr' ? `Découvrez ce produit : ${title}\nPrix : ${price}` : `Check out this product: ${title}\nPrice: ${price}`],
    [/^شاهد هذا المنتج المميز من متجري: (.+) - السعر: (.+)\. اطلبه الآن عبر التطبيق!$/, (title, price) => language === 'fr' ? `Découvrez ce produit de ma boutique : ${title} - Prix : ${price}. Commandez-le dans l’application !` : `Check out this product from my store: ${title} - Price: ${price}. Order now in the app!`],
    [/^المجموعات المطلوبة \((.+)\):$/, n => language === 'fr' ? `Groupes demandés (${n}) :` : `Requested groups (${n}):`],
    [/^إجمالي الكمية: (.+)$/, n => language === 'fr' ? `Quantité totale : ${n}` : `Total quantity: ${n}`],
    [/^([\d,]+) دج$/, n => `${n} DZD`],
    [/^([\d,]+) سنتيم$/, n => `${n} centimes`],
    [/^سجّل دخولك أو أنشئ حساباً مجانياً (.+)\.$/, n => language === 'fr' ? `Connectez-vous ou créez un compte gratuit ${n}.` : `Log in or create a free account ${n}.`],

    [/^(\d+)س$/, n => language === 'fr' ? `${n} h` : `${n} hr`],
    [/^(\d+)ي$/, n => language === 'fr' ? `${n} j` : `${n} d`],
  ];
  for (const [pattern, render] of templates) {
    const match = value.match(pattern);
    if (match) return render(...match.slice(1));
  }
  return value;
}

export function TText({ children, style, ...props }) {
  const { language } = useLanguage();
  const translateChild = (child) => {
    if (typeof child !== 'string') return child;
    const exact = translate(child, language);
    if (exact !== child) return exact;
    const patterned = translateKnownUiTemplate(child, language);
    if (patterned !== child) return patterned;
    const match = child.match(/^(\s*)([\s\S]*?)(\s*)$/);
    if (!match || !match[2]) return child;
    const trimmed = translate(match[2], language);
    return trimmed === match[2] ? child : `${match[1]}${trimmed}${match[3]}`;
  };
  const styles = Array.isArray(style) ? style : [style];
  const mapped = styles.map((item) => {
    if (!item || language === 'ar' || typeof item !== 'object') return item;
    return { ...item, ...(item.textAlign === 'right' ? { textAlign: 'left' } : {}), writingDirection: 'ltr' };
  });
  return React.createElement(require('react-native').Text, { ...props, style: mapped }, React.Children.map(children, translateChild));
}


export function LTextInput({ placeholder, ...props }) {
  const { language } = useLanguage();
  return React.createElement(require('react-native').TextInput, { ...props, placeholder: typeof placeholder === 'string' ? translate(placeholder, language) : placeholder });
}

export function translate(value, language = 'ar') {
  if (language === 'ar' || typeof value !== 'string') return value;
  const table = language === 'en' ? EN : FR;
  // Exact keys only: never rewrite user-entered product names, store names, or chat text.
  return Object.prototype.hasOwnProperty.call(table, value) ? table[value] : value;
}


export function useLocalizedAlert() {
  const { language } = useLanguage();
  return React.useCallback((title, message, buttons, options) => {
    const localize = (value) => typeof value === 'string' ? (translate(value, language) !== value ? translate(value, language) : translateKnownUiTemplate(value, language)) : value;
    const localizedButtons = Array.isArray(buttons)
      ? buttons.map((button) => ({ ...button, ...(typeof button?.text === 'string' ? { text: localize(button.text) } : {}) }))
      : buttons;
    return require('react-native').Alert.alert(localize(title), localize(message), localizedButtons, options);
  }, [language]);
}


export function showLocalizedAlert(title, message, buttons, options) {
  const localize = (value) => {
    if (typeof value !== 'string') return value;
    const translated = translate(value, activeLanguage);
    return translated !== value ? translated : translateKnownUiTemplate(value, activeLanguage);
  };
  const localizedButtons = Array.isArray(buttons)
    ? buttons.map((button) => ({ ...button, ...(typeof button?.text === 'string' ? { text: localize(button.text) } : {}) }))
    : buttons;
  return require('react-native').Alert.alert(localize(title), localize(message), localizedButtons, options);
}
